import { useEffect, useRef, useState, type FormEvent } from 'react';
import { ApiError, getLearningRoom, type LearningRoomBrief, type LearningState } from './api';
import { AttachmentDialog } from './AttachmentReview';
import SessionFeedback from './SessionFeedback';
import { CalibrationDetails, CommitmentPurge, commitmentConflict, commitmentFailure, commitmentKey, type CommitmentAttempt } from './LearningCommitmentSupport';
import { organizationRequestKey } from './learning-organization-api';
import { getLearningPath, type LearningPathVersion, type LearningPathView } from './learning-path-api';
import {
  cancelCommitmentSuggestion, changeCommitmentItem, confirmCommitmentDraft, getCommitmentContentPurge, getCommitmentSuggestion, getCommitmentSuggestionPurge, getLearningCommitments,
  previewCommitmentDraft, previewCommitmentItemChange, purgeCommitmentContent, purgeCommitmentSuggestion, saveCommitmentAvailability, saveCommitmentDraft, startCommitmentItem, startCommitmentSuggestion,
  type CommitmentAvailability, type CommitmentDraft, type CommitmentItem, type CommitmentItemInput, type CommitmentItemPreview, type CommitmentPreview, type CommitmentRun, type CommitmentRunSummary, type CommitmentView,
} from './learning-commitment-api';
import './styles/learning-commitments.css';

const localZone = () => Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC';
const dateInput = (value: string | null) => { if (!value) return ''; const date = new Date(value); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}T${String(date.getHours()).padStart(2, '0')}:${String(date.getMinutes()).padStart(2, '0')}`; };
const estimated = (item: CommitmentItem | CommitmentItemInput) => item.estimate_min_minutes === null ? '预计投入未知' : item.estimate_min_minutes === item.estimate_max_minutes ? `预计 ${item.estimate_min_minutes} 分钟` : `预计 ${item.estimate_min_minutes}–${item.estimate_max_minutes} 分钟`;
const statusLabel = { planned: '待开始', started: '已开始', deferred: '已延期', skipped: '已跳过', completed: '已完成' };
const runLabel = { running: '正在更新', succeeded: '已有候选草案', failed: '未完成', canceled: '已取消', purged: '内容已清除' };
const itemInput = (item: CommitmentItem): CommitmentItemInput => ({ id: item.id, node_id: item.node_id, action_id: item.action_id, delegation_id: item.delegation_id, estimate_min_minutes: item.estimate_min_minutes, estimate_max_minutes: item.estimate_max_minutes, due_at: item.due_at, timezone: item.timezone, reason: item.reason ?? '', source_refs: item.source_refs ?? [] });

export default function LearningCommitments({ planId, state, onLearning, onOpenRecord, onRefresh, closed }: {
  planId: string; state: LearningState; onLearning: (brief: LearningRoomBrief) => void; onOpenRecord: (delegationId: string) => void; onRefresh: () => Promise<void>; closed: boolean;
}) {
  const [view, setView] = useState<CommitmentView | null>(null), [path, setPath] = useState<LearningPathView | null>(null), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const [editor, setEditor] = useState<{ draft?: CommitmentDraft; route: LearningPathVersion } | null>(null), [previewDraft, setPreviewDraft] = useState<CommitmentDraft | null>(null), [changing, setChanging] = useState<{ item: CommitmentItem; operation: 'defer' | 'skip' } | null>(null), [availability, setAvailability] = useState(false), [run, setRun] = useState<CommitmentRun | null>(null), [missingAnchor, setMissingAnchor] = useState<string | null>(null);
  const identity = useRef(planId); identity.current = planId;
  const serial = useRef(0), attempt = useRef<CommitmentAttempt>(null);
  async function read(restoreRun = false) {
    const sequence = ++serial.current;
    const [next, route] = await Promise.all([getLearningCommitments(planId), getLearningPath(planId)]);
    if (identity.current === planId && sequence === serial.current) {
      setView(next); setPath(route); setError(''); setLoading(false);
      if (restoreRun) { const latest = next.runs?.find(value => value.status === 'running') ?? next.runs?.[0]; if (latest) { const value = await getCommitmentSuggestion(planId, latest.id); if (identity.current === planId && sequence === serial.current) setRun(value); } }
    }
    return { next, route };
  }
  async function refresh() { const next = await read(true); await onRefresh(); return next; }
  async function changed(next: CommitmentView) { setView(next); await onRefresh(); }
  useEffect(() => { setView(null); setPath(null); setLoading(true); setError(''); setEditor(null); setPreviewDraft(null); setRun(null); setChanging(null); setMissingAnchor(null); attempt.current = null; void read(true).catch(reason => { if (identity.current === planId) { setError(commitmentFailure(reason)); setLoading(false); } }); return () => { serial.current++; }; }, [planId]);
  useEffect(() => {
    if (run?.status !== 'running') return;
    let active = true, timer: number | undefined;
    async function poll() {
      try { const next = await getCommitmentSuggestion(planId, run!.id); if (!active || identity.current !== planId) return; setRun(next); if (next.status !== 'running') await read(); else timer = window.setTimeout(() => void poll(), 1000); }
      catch (reason) { if (active) { setError(commitmentFailure(reason)); timer = window.setTimeout(() => void poll(), 2500); } }
    }
    timer = window.setTimeout(() => void poll(), 800);
    return () => { active = false; window.clearTimeout(timer); };
  }, [planId, run?.id, run?.status]);
  const route = path?.versions.find(value => value.id === path.adopted_version_id && value.content_available);
  const writable = !closed && !!route && path?.status === 'active';
  const items = view?.current_version?.items ?? [];
  const nextItem = items.find(item => item.status === 'started' && state.sessions.some(session => item.execution_session_ids.includes(session.id) && session.status === 'running')) ?? items.find(item => ['planned', 'started'].includes(item.status));
  const candidates = view?.drafts.filter(draft => draft.status === 'draft' && draft.content_available) ?? [];
  const updating = run?.status === 'running' || view?.runs?.some(value => value.status === 'running');
  async function suggest() {
    if (!view || !writable || busy) return; setBusy(true); setError('');
    const body = { expected_revision: view.revision };
    try { setRun(await startCommitmentSuggestion(planId, view.revision, commitmentKey(attempt, body))); attempt.current = null; }
    catch (reason) { setError(commitmentFailure(reason)); }
    finally { setBusy(false); }
  }
  async function cancel() { if (!run) return; setBusy(true); setError(''); try { setRun(await cancelCommitmentSuggestion(planId, run.id, run.revision, organizationRequestKey())); await read(); } catch (reason) { setError(commitmentFailure(reason)); } finally { setBusy(false); } }
  async function start(item: CommitmentItem, useCheckpoint = true) {
    if (!view || !writable || busy) return;
    const action = state.actions.find(value => value.id === item.action_id); if (!action || action.status !== 'open') return;
    const body = { expected_action_version: action.version, expected_revision: view.revision, use_checkpoint: useCheckpoint }; setBusy(true); setError('');
    try { const result = await startCommitmentItem(planId, item.id, { ...body, request_key: commitmentKey(attempt, { item_id: item.id, ...body }) }, item.execution_session_ids.length > 0); const room = await getLearningRoom(result.session_id); attempt.current = null; setMissingAnchor(null); onLearning(Object.assign({}, room.brief, result.path_anchor ? { path_anchor: result.path_anchor } : {})); }
    catch (reason) { setError(commitmentFailure(reason)); if (reason instanceof ApiError && reason.kind === 'path_anchor_unavailable') setMissingAnchor(item.id); }
    finally { setBusy(false); }
  }
  function renderItem(item: CommitmentItem, primary = false) {
    const action = state.actions.find(value => value.id === item.action_id), open = action?.status === 'open' && !['completed', 'skipped'].includes(item.status);
    const linkedSessions = item.execution_session_ids.map(id => state.sessions.find(session => session.id === id)).filter(session => !!session);
    const stopped = linkedSessions.some(session => session.status === 'running') ? null : [...linkedSessions].reverse().find(session => session.status !== 'running');
    return <article key={item.id} className={`commitment-item ${primary ? 'commitment-item--next' : ''}`} data-commitment-item={item.id}>
      <div><small>{primary ? '下一项' : statusLabel[item.status]}</small><h4>{action?.title ?? '任务当前不可查看'}</h4><p>{estimated(item)} · {item.due_at ? new Date(item.due_at).toLocaleString() : '日期未知'}</p></div>
      <div className="commitment-actions">{open && <button className={`button ${primary ? 'button--accent' : 'button--quiet'}`} type="button" disabled={!writable || busy} onClick={() => void start(item)}>{item.execution_session_ids.length ? '继续学习' : '开始学习'}</button>}<button className="text-button" type="button" onClick={() => onOpenRecord(item.delegation_id)}>{item.status === 'completed' ? '回看记录' : '查看记录'}</button>{open && <><button className="text-button" type="button" disabled={!writable || busy} onClick={() => setChanging({ item, operation: 'defer' })}>改期</button><button className="text-button" type="button" disabled={!writable || busy} onClick={() => setChanging({ item, operation: 'skip' })}>跳过</button></>}</div>
      {missingAnchor === item.id && <button className="button button--quiet" type="button" disabled={!writable || busy} onClick={() => void start(item, false)}>从当前可用任务开始</button>}
      {!!item.reason && <details><summary>为什么安排这一步</summary><p>{item.reason}</p></details>}
      {stopped && <SessionFeedback key={stopped.id} sessionId={stopped.id} onSaved={async () => { await refresh(); }} />}
    </article>;
  }
  function clearDraft(draftId: string, label: string, retry = false) { if (!view) return null; return <div key={draftId}><CommitmentPurge title="清除安排说明" description="清除这份安排的说明文字及管理范围内副本。已确认安排的任务、顺序、预计与执行事实保留；尚未确认的草案不再采用。" available readStatus={async () => { const [report, latest] = await Promise.all([getCommitmentContentPurge(planId, draftId), getLearningCommitments(planId)]); setView(latest); return report; }} retryNeeded={retry} purge={async key => { const result = await purgeCommitmentContent(planId, draftId, view.revision, key); setView(result); return result.purge_report; }} onDone={onRefresh} />{label && <span className="commitment-muted">{label}</span>}</div>; }
  function runPurge(value: CommitmentRunSummary) { return <CommitmentPurge title="清除这次更新内容" description="清除这次更新的私有输入及管理范围内副本，相关未采用草案不再使用。任务和执行事实保留。" available={value.can_purge_content ?? true} retryNeeded={value.purge_retry_needed} readStatus={async () => { const [report, latest] = await Promise.all([getCommitmentSuggestionPurge(planId, value.id), getCommitmentSuggestion(planId, value.id)]); if (run?.id === value.id) setRun(latest); await read(); return report; }} purge={async key => { const result = await purgeCommitmentSuggestion(planId, value.id, value.revision, key); if (run?.id === value.id) setRun(result); await read(); return result.purge_report; }} />; }
  return <section className="learning-commitments" aria-label="近期安排">
    <div className="commitment-toolbar"><p>{view?.route_status === 'paused' ? '当前方向已暂停，请先在路径中恢复。' : !route && !loading ? '先在路径中明确几个阶段，再安排近期学习。' : '先完成下一项，再用实际记录调整。'}</p><div className="commitment-actions"><button className="button button--quiet" type="button" disabled={!writable || busy || updating} onClick={() => { if (route) setEditor({ route }); }}>手动安排</button><button className="button button--accent" type="button" disabled={!writable || busy || updating} onClick={() => void suggest()}>更新近期安排</button></div></div>
    {loading && <p role="status">正在读取近期安排…</p>}{error && <div role="alert"><p>{error}</p><button className="text-button" type="button" disabled={busy} onClick={() => void refresh().catch(reason => setError(commitmentFailure(reason)))}>读取最新安排</button></div>}
    {run && <div className="commitment-run">{run.status === 'running' ? <><p role="status">正在提出近期安排…确认前不会改变安排。</p><button className="text-button" type="button" disabled={busy} onClick={() => void cancel()}>取消更新</button></> : run.status === 'failed' ? <p role="alert">{commitmentFailure(run.reason)}</p> : run.status === 'canceled' ? <p>已取消更新，现有安排保留。</p> : null}<details><summary>这次更新详情</summary><p>{new Date(run.created_at).toLocaleString()} · {runLabel[run.status]}</p>{runPurge(run)}</details></div>}
    {nextItem ? renderItem(nextItem, true) : view && <p className="commitment-empty">{items.length ? '这轮没有待开始的安排，可回看记录或明确下一步。' : '还没有近期安排。可以先手动写下下一步，日期留空。'}</p>}
    {items.some(item => item.id !== nextItem?.id) && <details className="commitment-rest"><summary>其他安排与已发生记录</summary><div>{items.filter(item => item.id !== nextItem?.id).map(item => renderItem(item))}</div></details>}
    {!!candidates.length && <section className="commitment-candidates" aria-label="候选安排"><h4>待核对的安排</h4>{candidates.map(draft => <article key={draft.id}><p>{draft.source === 'ai' ? 'AI 建议' : '本人草案'} · {draft.items.length} 项</p><div className="commitment-actions"><button className="button button--quiet" type="button" disabled={!writable || busy} onClick={() => setPreviewDraft(draft)}>查看确认预览</button><button className="text-button" type="button" disabled={!writable || busy} onClick={() => { if (route) setEditor({ draft, route }); }}>逐项编辑</button></div><details><summary>草案详情</summary>{draft.items.map(item => <p key={item.id}>{state.actions.find(value => value.id === item.action_id)?.title ?? '任务'} · {estimated(item)}</p>)}{draft.reason && <p>{draft.reason}</p>}{clearDraft(draft.id, '')}</details></article>)}</section>}
    {view && <><CalibrationDetails value={view.calibration} /><details><summary>可用时段与预算（可选）</summary><p>{view.availability ? `本人给出的时区：${view.availability.timezone}` : '可先留空；不会把预算当作实际投入。'}</p><button className="text-button" type="button" disabled={!writable || busy} onClick={() => setAvailability(true)}>填写可用时间</button></details>
      {!!view.versions.length && <details><summary>安排历史与内容清除</summary>{view.versions.map(version => <article key={version.id}><p>{new Date(version.created_at).toLocaleString()} · {version.items.length} 项 · {version.source === 'ai' ? '已确认的 AI 建议' : '本人安排'}</p>{version.reason && <p>{version.reason}</p>}<details><summary>当时安排与记录</summary>{version.items.map(item => <div key={item.id}><p>{state.actions.find(value => value.id === item.action_id)?.title ?? '任务'} · {estimated(item)} · {statusLabel[item.status]}</p><button className="text-button" type="button" onClick={() => onOpenRecord(item.delegation_id)}>回看记录</button></div>)}</details>{version.can_purge_content && clearDraft(version.draft_id, '', view.purge_retry_ids?.includes(version.draft_id))}</article>)}</details>}
      {!!view.purge_retry_ids?.length && <details><summary>尚未完成的安排清除</summary>{view.purge_retry_ids.map(id => clearDraft(id, '', true))}</details>}
      {!!view.runs?.length && <details className="commitment-run-history"><summary>更新历史与内容清除</summary>{view.runs.map(value => <article key={value.id} data-commitment-run={value.id}><p>{new Date(value.created_at).toLocaleString()} · {runLabel[value.status]}</p>{value.status === 'failed' && <p>{commitmentFailure(value.reason)}</p>}{runPurge(value)}</article>)}</details>}</>}
    {editor && view && <CommitmentEditor planId={planId} state={state} view={view} route={editor.route} draft={editor.draft} closed={closed} onClose={() => setEditor(null)} onRead={refresh} onSaved={async (next, draft) => { await changed(next); setEditor(null); setPreviewDraft(draft); }} />}
    {previewDraft && view && <CommitmentConfirm planId={planId} draft={previewDraft} state={state} view={view} closed={closed} onClose={() => setPreviewDraft(null)} onRead={refresh} onConfirmed={async next => { await changed(next); setPreviewDraft(null); }} />}
    {changing && view && <CommitmentChange planId={planId} state={state} item={changing.item} operation={changing.operation} closed={closed} onClose={() => setChanging(null)} onChanged={async next => { await changed(next); setChanging(null); }} />}
    {availability && view && <AvailabilityEditor planId={planId} view={view} closed={closed} onClose={() => setAvailability(false)} onRead={refresh} onSaved={async next => { await changed(next); setAvailability(false); }} />}
  </section>;
}

function CommitmentEditor({ planId, state, view, route, draft, closed, onClose, onRead, onSaved }: {
  planId: string; state: LearningState; view: CommitmentView; route: LearningPathVersion; draft?: CommitmentDraft; closed: boolean; onClose: () => void;
  onRead: () => Promise<{ next: CommitmentView; route: LearningPathView }>; onSaved: (next: CommitmentView, draft: CommitmentDraft) => Promise<void>;
}) {
  const base = draft ?? (view.current_version?.content_available ? view.current_version : undefined);
  const [activeRoute, setActiveRoute] = useState<LearningPathVersion | null>(route);
  const [items, setItems] = useState<CommitmentItemInput[]>(() => base?.items.map(itemInput) ?? []), [reason, setReason] = useState(base?.reason ?? ''), [busy, setBusy] = useState(false), [error, setError] = useState(''), [conflict, setConflict] = useState(false), [checked, setChecked] = useState(false), [revision, setRevision] = useState(view.revision), [draftRevision, setDraftRevision] = useState(draft?.revision), [scope, setScope] = useState('1');
  const attempt = useRef<CommitmentAttempt>(null);
  const executed = new Set(base?.items.filter(item => item.execution_session_ids.length > 0 || ['completed', 'skipped'].includes(item.status)).map(item => item.id));
  const routes = activeRoute?.nodes ?? [];
  function update(index: number, change: Partial<CommitmentItemInput>) { setItems(previous => previous.map((item, i) => i === index ? { ...item, ...change } : item)); }
  function add() { const node = routes.find(node => node.id === view.current_node_id && node.action_ids.some(id => state.actions.some(action => action.id === id && action.status === 'open'))) ?? routes.find(node => node.action_ids.some(id => state.actions.some(action => action.id === id && action.status === 'open'))); setItems(previous => [...previous, { id: null, node_id: node?.id ?? '', action_id: '', delegation_id: '', estimate_min_minutes: null, estimate_max_minutes: null, due_at: null, timezone: null, reason: '', source_refs: [] }]); }
  async function read() { setBusy(true); setError(''); try { const latest = await onRead(); setRevision(latest.next.revision); setActiveRoute(latest.route.status === 'active' ? latest.route.versions.find(value => value.id === latest.route.adopted_version_id && value.content_available) ?? null : null); setDraftRevision(latest.next.drafts.find(value => value.id === draft?.id)?.revision); setChecked(true); } catch (value) { setError(commitmentFailure(value)); } finally { setBusy(false); } }
  async function save(event: FormEvent) {
    event.preventDefault(); if (busy || conflict || closed || !activeRoute) return;
    if (items.some(item => !item.node_id || !item.action_id || !item.delegation_id)) { setError('请为每项明确选择阶段与任务。'); return; }
    if (items.some(item => (item.estimate_min_minutes === null) !== (item.estimate_max_minutes === null) || item.estimate_min_minutes !== null && item.estimate_max_minutes! < item.estimate_min_minutes)) { setError('请填写完整预计范围，或两项都留空。'); return; }
    const body = { route_version_id: activeRoute.id, items, reason, draft_id: draft?.id ?? null, ...(draft ? { expected_draft_revision: draftRevision } : {}), expected_revision: revision }; setBusy(true); setError('');
    try { const next = await saveCommitmentDraft(planId, { ...body, request_key: commitmentKey(attempt, body) }); const value = next.drafts.find(value => value.id === next.draft_id); if (!value) throw new Error('已保存，但草案当前不可读取。请重新读取安排。'); attempt.current = null; await onSaved(next, value); }
    catch (value) { setError(commitmentFailure(value)); if (commitmentConflict(value)) { setConflict(true); setChecked(false); } }
    finally { setBusy(false); }
  }
  return <AttachmentDialog title={draft?.source === 'ai' ? '编辑建议安排' : '手动安排'} className="commitment-dialog" closeLabel="关闭安排编辑" onClose={() => { if (!busy) onClose(); }}><form onSubmit={event => void save(event)}><div className="commitment-dialog-body">
    <p className="commitment-muted">先明确任务顺序与范围；日期和预计投入都可以未知。</p>
    {items.length > 1 && <div className="commitment-shorten"><label className="field"><span>近期先保留几项</span><input type="number" min={1} max={items.length} value={scope} onChange={event => setScope(event.target.value)} /></label><button className="text-button" type="button" disabled={busy} onClick={() => setItems(previous => previous.filter((item, index) => index < Math.max(1, Number(scope)) || !!item.id && executed.has(item.id)))}>缩小范围</button></div>}
    <div className="commitment-editor-items">{items.map((item, index) => { const lock = !!item.id && executed.has(item.id), node = routes.find(value => value.id === item.node_id), options = state.delegations.filter(value => node?.action_ids.includes(value.action_id) && ['ready', 'active'].includes(value.status) && state.actions.some(action => action.id === value.action_id && action.status === 'open'));
      return <fieldset key={item.id ?? index} className="commitment-editor-item"><legend>安排 {index + 1}</legend><div className="commitment-field-grid"><label className="field"><span>关联阶段</span><select aria-label="关联阶段" disabled={lock || !!item.id || busy} value={item.node_id} onChange={event => update(index, { node_id: event.target.value, action_id: '', delegation_id: '' })}><option value="">请选择</option>{!node && item.node_id && <option value={item.node_id}>原方向阶段（保留记录）</option>}{routes.map(value => <option key={value.id} value={value.id}>{value.title}</option>)}</select></label><label className="field"><span>计划任务</span><select aria-label="计划任务" disabled={lock || !!item.id || busy} value={item.delegation_id} onChange={event => { const delegation = options.find(value => value.id === event.target.value); update(index, { delegation_id: delegation?.id ?? '', action_id: delegation?.action_id ?? '' }); }}><option value="">请选择</option>{!options.some(value => value.id === item.delegation_id) && item.delegation_id && <option value={item.delegation_id}>{state.actions.find(value => value.id === item.action_id)?.title ?? '原任务（保留记录）'}</option>}{options.map(value => <option key={value.id} value={value.id}>{value.action_title}</option>)}</select></label></div>
        <details><summary>预计投入、日期与理由</summary><div className="commitment-field-grid"><label className="field"><span>预计至少（分钟）</span><input type="number" min={1} max={10080} disabled={lock || busy} value={item.estimate_min_minutes ?? ''} onChange={event => update(index, { estimate_min_minutes: event.target.value === '' ? null : Number(event.target.value) })} /></label><label className="field"><span>预计至多（分钟）</span><input type="number" min={1} max={10080} disabled={lock || busy} value={item.estimate_max_minutes ?? ''} onChange={event => update(index, { estimate_max_minutes: event.target.value === '' ? null : Number(event.target.value) })} /></label><label className="field"><span>日期（可留空）</span><input type="datetime-local" disabled={lock || busy} value={dateInput(item.due_at)} onChange={event => update(index, { due_at: event.target.value ? new Date(event.target.value).toISOString() : null, timezone: event.target.value ? localZone() : null })} /></label></div><label className="field"><span>安排理由（可选）</span><textarea aria-label="安排理由（可选）" maxLength={2000} value={item.reason} onChange={event => update(index, { reason: event.target.value })} /></label>{lock && <p className="commitment-muted">已执行部分保留原预计；改期或跳过请使用安排列表中的预览。</p>}</details>
        <div className="commitment-actions"><button className="text-button" type="button" disabled={busy || index === 0} onClick={() => setItems(previous => { const next = [...previous]; [next[index - 1], next[index]] = [next[index], next[index - 1]]; return next; })}>向上</button><button className="text-button" type="button" disabled={busy || index === items.length - 1} onClick={() => setItems(previous => { const next = [...previous]; [next[index + 1], next[index]] = [next[index], next[index + 1]]; return next; })}>向下</button><button className="text-button" type="button" disabled={busy || lock} onClick={() => setItems(previous => previous.filter((_, i) => i !== index))}>移出近期范围</button></div>
      </fieldset>;
    })}</div><button className="button button--quiet" type="button" disabled={busy || items.length >= (draft?.source === 'ai' ? view.calibration.max_sessions : 100)} onClick={add}>添加一项</button><label className="field"><span>这次安排的说明（可选）</span><textarea aria-label="这次安排的说明（可选）" maxLength={2000} value={reason} onChange={event => setReason(event.target.value)} /></label>
    {error && <p role="alert">{error}</p>}{conflict && <div><p>编辑内容已保留。请读取最新状态，再核对任务与范围。</p><button className="text-button" type="button" disabled={busy} onClick={() => void read()}>读取最新状态</button>{checked && activeRoute && <button className="text-button" type="button" onClick={() => { setConflict(false); setError(''); attempt.current = null; }}>已核对，继续编辑</button>}{checked && !activeRoute && <p>当前路径不可安排，请先恢复或建立可用路径。输入仍保留。</p>}</div>}
    </div><footer className="commitment-dialog-footer"><button className="button button--quiet" type="button" disabled={busy} onClick={onClose}>取消</button><button className="button button--accent" type="submit" disabled={busy || conflict || closed || !activeRoute}>保存草案并预览</button></footer></form></AttachmentDialog>;
}

function CommitmentConfirm({ planId, draft, state, view, closed, onClose, onRead, onConfirmed }: { planId: string; draft: CommitmentDraft; state: LearningState; view: CommitmentView; closed: boolean; onClose: () => void; onRead: () => Promise<{ next: CommitmentView; route: LearningPathView }>; onConfirmed: (view: CommitmentView) => Promise<void> }) {
  const [displayDraft, setDisplayDraft] = useState(draft), [preview, setPreview] = useState<CommitmentPreview | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState(''); const attempt = useRef<CommitmentAttempt>(null);
  async function review() { setBusy(true); setError(''); setPreview(null); try { const latest = await onRead(); const current = latest.next.drafts.find(value => value.id === draft.id && value.status === 'draft' && value.content_available); if (!current) throw new Error('这份草案已经确认或清除，请关闭后查看最新安排。'); setDisplayDraft(current); const result = await previewCommitmentDraft(planId, draft.id); if (result.draft_revision !== current.revision) throw new Error('草案刚有变化，请重新读取并预览。'); setPreview(result); } catch (reason) { setError(commitmentFailure(reason)); } finally { setBusy(false); } }
  useEffect(() => { void review(); }, [draft.id]);
  async function confirm() { if (!preview || busy || closed) return; setBusy(true); setError(''); const body = { draft_id: draft.id, expected_draft_revision: preview.draft_revision, expected_revision: preview.revision, review_key: preview.review_key }; try { await onConfirmed(await confirmCommitmentDraft(planId, { ...body, request_key: commitmentKey(attempt, body) })); } catch (reason) { setError(commitmentFailure(reason)); setPreview(null); } finally { setBusy(false); } }
  const all = [...displayDraft.items, ...(view.current_version?.items ?? [])];
  return <AttachmentDialog title="确认近期安排" className="commitment-dialog commitment-preview" closeLabel="关闭安排预览" onClose={() => { if (!busy) onClose(); }}><div className="commitment-dialog-body"><h3>将采用的顺序与范围</h3><ol>{displayDraft.items.map(item => <li key={item.id}>{state.actions.find(value => value.id === item.action_id)?.title ?? '任务'} · {estimated(item)} · {item.due_at ? new Date(item.due_at).toLocaleString() : '日期未知'}</li>)}</ol>{preview && <><h4>现有安排的变化</h4><ul>{preview.changes.map(change => { const item = all.find(item => item.id === change.item_id); return <li key={change.item_id}>{change.kind === 'defer' ? '移出近期范围，延期未执行部分' : change.kind === 'keep' ? '保留' : '采用调整'} · {state.actions.find(action => action.id === item?.action_id)?.title ?? '安排'}{change.executed && ' · 已发生记录保留'}</li>; })}</ul><CalibrationDetails value={preview.calibration} /></>}<p className="commitment-muted">确认只保存近期安排。需要学习时，再明确开始。</p>{busy && !preview && <p role="status">正在核对…</p>}{error && <p role="alert">{error}</p>}{!preview && !busy && <button className="text-button" type="button" onClick={() => void review()}>读取最新状态并重新预览</button>}</div><footer className="commitment-dialog-footer"><button className="button button--quiet" type="button" disabled={busy} onClick={onClose}>取消</button><button className="button button--accent" type="button" disabled={busy || !preview || closed} onClick={() => void confirm()}>确认采用安排</button></footer></AttachmentDialog>;
}

function CommitmentChange({ planId, state, item, operation, closed, onClose, onChanged }: { planId: string; state: LearningState; item: CommitmentItem; operation: 'defer' | 'skip'; closed: boolean; onClose: () => void; onChanged: (view: CommitmentView) => Promise<void> }) {
  const [date, setDate] = useState(operation === 'defer' ? dateInput(item.due_at) : ''), [preview, setPreview] = useState<CommitmentItemPreview | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState(''); const attempt = useRef<CommitmentAttempt>(null);
  async function review() { setBusy(true); setError(''); try { setPreview(await previewCommitmentItemChange(planId, item.id, operation, date ? new Date(date).toISOString() : null, date ? localZone() : null)); } catch (reason) { setError(commitmentFailure(reason)); setPreview(null); } finally { setBusy(false); } }
  async function confirm() { if (!preview || busy || closed) return; setBusy(true); setError(''); const body = { expected_revision: preview.revision, review_key: preview.review_key, due_at: preview.due_at, timezone: preview.timezone }; try { await onChanged(await changeCommitmentItem(planId, item.id, operation, { ...body, request_key: commitmentKey(attempt, body) })); } catch (reason) { setError(commitmentFailure(reason)); setPreview(null); } finally { setBusy(false); } }
  return <AttachmentDialog title={operation === 'defer' ? '改期' : '跳过这项安排'} className="commitment-dialog commitment-change" closeLabel="关闭安排变更" onClose={() => { if (!busy) onClose(); }}><div className="commitment-dialog-body"><h3>{state.actions.find(value => value.id === item.action_id)?.title}</h3>{operation === 'defer' && <label className="field"><span>新的日期（可留空）</span><input type="datetime-local" value={date} onChange={event => { setDate(event.target.value); setPreview(null); }} /></label>}<p>已发生的学习、产出与完成记录保留。</p>{preview ? <><p>{operation === 'defer' ? preview.due_at ? `将改到 ${new Date(preview.due_at).toLocaleString()}` : '延期，日期暂不确定。' : '这项安排将标记为已跳过。'}</p>{!!preview.affected_sessions.length && <section><h4>确认后暂停相关学习</h4>{preview.affected_sessions.map(session => <p key={session.id}>{state.actions.find(value => value.id === session.action_id)?.title ?? '学习任务'}</p>)}</section>}</> : <button className="button button--quiet" type="button" disabled={busy || closed} onClick={() => void review()}>查看影响预览</button>}{error && <p role="alert">{error}</p>}</div><footer className="commitment-dialog-footer"><button className="button button--quiet" type="button" disabled={busy} onClick={onClose}>取消</button><button className="button button--accent" type="button" disabled={busy || !preview || closed} onClick={() => void confirm()}>{operation === 'defer' ? '确认改期' : '确认跳过'}</button></footer></AttachmentDialog>;
}

function AvailabilityEditor({ planId, view, closed, onClose, onRead, onSaved }: { planId: string; view: CommitmentView; closed: boolean; onClose: () => void; onRead: () => Promise<{ next: CommitmentView; route: LearningPathView }>; onSaved: (view: CommitmentView) => Promise<void> }) {
  const zone = localZone(); const [slots, setSlots] = useState(view.availability?.slots.map(slot => ({ start: dateInput(slot.start_at), end: dateInput(slot.end_at) })) ?? []), [budget, setBudget] = useState(view.availability?.weekly_budget_minutes?.toString() ?? ''), [block, setBlock] = useState(view.availability?.block_max_minutes?.toString() ?? ''), [days, setDays] = useState<7 | 14>(view.availability?.preferred_days ?? 7), [revision, setRevision] = useState(view.revision), [busy, setBusy] = useState(false), [error, setError] = useState(''), [conflict, setConflict] = useState(false), [checked, setChecked] = useState(false); const attempt = useRef<CommitmentAttempt>(null);
  async function save(event: FormEvent) { event.preventDefault(); if (busy || conflict || closed) return; if (slots.some(slot => !slot.start || !slot.end || new Date(slot.end) <= new Date(slot.start))) { setError('请填完整且结束晚于开始的时段，或移除未知时段。'); return; } const value: CommitmentAvailability = { timezone: zone, slots: slots.map(slot => ({ start_at: new Date(slot.start).toISOString(), end_at: new Date(slot.end).toISOString() })), weekly_budget_minutes: budget ? Number(budget) : null, block_max_minutes: block ? Number(block) : null, preferred_days: days }; const body = { ...value, expected_revision: revision }; setBusy(true); setError(''); try { await onSaved(await saveCommitmentAvailability(planId, { ...body, request_key: commitmentKey(attempt, body) })); } catch (reason) { setError(commitmentFailure(reason)); if (commitmentConflict(reason)) { setConflict(true); setChecked(false); } } finally { setBusy(false); } }
  return <AttachmentDialog title="可用时间" className="commitment-dialog" closeLabel="关闭可用时间" onClose={() => { if (!busy) onClose(); }}><form onSubmit={event => void save(event)}><div className="commitment-dialog-body"><p className="commitment-muted">时段按这台设备的当地时间填写；没有把握可暂不填写。</p><label className="field"><span>时区</span><input value={zone} readOnly /></label>{slots.map((slot, index) => <fieldset key={index}><legend>可用时段 {index + 1}</legend><div className="commitment-field-grid"><label className="field"><span>开始</span><input type="datetime-local" value={slot.start} onChange={event => setSlots(previous => previous.map((value, i) => i === index ? { ...value, start: event.target.value } : value))} /></label><label className="field"><span>结束</span><input type="datetime-local" value={slot.end} onChange={event => setSlots(previous => previous.map((value, i) => i === index ? { ...value, end: event.target.value } : value))} /></label></div><button className="text-button" type="button" onClick={() => setSlots(previous => previous.filter((_, i) => i !== index))}>移除时段</button></fieldset>)}<button className="text-button" type="button" disabled={slots.length >= 60} onClick={() => setSlots(previous => [...previous, { start: '', end: '' }])}>添加可用时段</button><div className="commitment-field-grid"><label className="field"><span>一周可用预算（分钟，可留空）</span><input type="number" min={1} max={10080} value={budget} onChange={event => setBudget(event.target.value)} /></label><label className="field"><span>每次至多（分钟，可留空）</span><input type="number" min={1} max={1440} value={block} onChange={event => setBlock(event.target.value)} /></label><label className="field"><span>希望看多远</span><select value={days} onChange={event => setDays(Number(event.target.value) as 7 | 14)}><option value={7}>近期一周</option><option value={14}>近期两周</option></select></label></div>{error && <p role="alert">{error}</p>}{conflict && <div><p>输入已保留，请重新核对最新安排。</p><button className="text-button" type="button" disabled={busy} onClick={() => { setBusy(true); void onRead().then(value => { setRevision(value.next.revision); setChecked(true); }).catch(value => setError(commitmentFailure(value))).finally(() => setBusy(false)); }}>读取最新状态</button>{checked && <button className="text-button" type="button" onClick={() => { setConflict(false); setError(''); attempt.current = null; }}>已核对，继续编辑</button>}</div>}</div><footer className="commitment-dialog-footer"><button className="button button--quiet" type="button" disabled={busy} onClick={onClose}>取消</button><button className="button button--accent" type="submit" disabled={busy || closed || conflict}>保存可用时间</button></footer></form></AttachmentDialog>;
}
