import { useEffect, useRef, useState, type FormEvent } from 'react';
import { CommitmentPurge, commitmentConflict, commitmentFailure, commitmentKey, type CommitmentAttempt } from './LearningCommitmentSupport';
import { getSessionFeedback, getSessionFeedbackPurge, purgeSessionFeedback, recordSessionFeedback, type SessionFeedbackInput, type SessionFeedbackRecord, type SessionFeedbackView } from './learning-commitment-api';
import './styles/learning-commitments.css';

const empty = (): SessionFeedbackInput => ({ actual_min_minutes: null, actual_max_minutes: null, purpose: 'unknown', grain: 'unknown', pace: 'unknown', method_feedback: 'unknown', progress: 'uncertain', activity: 'learning', artifact_id: null, artifact_version: null, submission_id: null, delayed_attempt_id: null, notes: '' });
const values = (record: SessionFeedbackRecord): SessionFeedbackInput => ({ actual_min_minutes: record.actual_min_minutes, actual_max_minutes: record.actual_max_minutes, purpose: record.purpose, grain: record.grain, pace: record.pace, method_feedback: record.method_feedback, progress: record.progress, activity: record.activity, artifact_id: record.artifact_id, artifact_version: record.artifact_version, submission_id: record.submission_id, delayed_attempt_id: record.delayed_attempt_id, notes: record.notes ?? '' });
const purposeLabels = { real: '实际学习', test: '演示或测试', unknown: '尚不确定' };
const progressLabels = { progress: '有所进展', difficulty: '仍有困难', uncertain: '还不确定' };
function FeedbackSummary({ value }: { value: SessionFeedbackRecord }) {
  const grain = { unknown: '未知', ok: '合适', too_large: '太大', too_small: '太小' }, pace = { unknown: '未知', ok: '合适', too_tight: '太紧', want_more: '想再多做一点' }, method = { unknown: '未知', ok: '合适', unsuitable: '不合适' }, activity = { learning: '学习', recall: '回忆', variation: '变式练习', transfer: '迁移尝试' };
  return <div className="session-feedback-summary"><p>{purposeLabels[value.purpose]} · {progressLabels[value.progress]} · {value.actual_min_minutes === null ? '有效投入未知' : value.actual_min_minutes === value.actual_max_minutes ? `本人记录投入 ${value.actual_min_minutes} 分钟` : `本人记录投入 ${value.actual_min_minutes}–${value.actual_max_minutes} 分钟`}</p>{value.notes && <p>{value.notes}</p>}{value.association_label && <p>{value.association_label}</p>}<details><summary>体验细节与关联</summary><p>任务大小：{grain[value.grain]} · 节奏：{pace[value.pace]} · 方法：{method[value.method_feedback]} · 主要活动：{activity[value.activity]}</p>{value.artifact_id && <p>本人关联了本次学习产出。</p>}{value.submission_id && <p>本人关联了本次学习作答。</p>}</details></div>;
}
export default function SessionFeedback({ sessionId, onSaved }: { sessionId: string; onSaved?: () => Promise<void> | void }) {
  const [open, setOpen] = useState(false), [view, setView] = useState<SessionFeedbackView | null>(null), [form, setForm] = useState(empty), [editing, setEditing] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState(''), [conflict, setConflict] = useState(false), [checked, setChecked] = useState(false);
  const identity = useRef(sessionId); identity.current = sessionId;
  const attempt = useRef<CommitmentAttempt>(null);
  useEffect(() => { setOpen(false); setView(null); setForm(empty()); setEditing(false); setBusy(false); setError(''); setConflict(false); attempt.current = null; }, [sessionId]);
  async function read(preserve = false) {
    setBusy(true); setError('');
    try { const next = await getSessionFeedback(sessionId); if (identity.current !== sessionId) return; setView(next); if (!preserve) { setForm(next.current ? values(next.current) : empty()); setEditing(!next.current && !next.purged); } else setChecked(true); }
    catch (reason) { if (identity.current === sessionId) setError(commitmentFailure(reason)); }
    finally { if (identity.current === sessionId) setBusy(false); }
  }
  function update<K extends keyof SessionFeedbackInput>(key: K, value: SessionFeedbackInput[K]) { setForm(previous => ({ ...previous, [key]: value })); }
  async function save(event: FormEvent) {
    event.preventDefault(); if (!view || busy || conflict) return;
    if ((form.actual_min_minutes === null) !== (form.actual_max_minutes === null) || (form.actual_min_minutes !== null && form.actual_max_minutes! < form.actual_min_minutes)) { setError('请填写完整投入范围，或两项都留空。'); return; }
    const body = { ...form, expected_revision: view.revision }; setBusy(true); setError('');
    try { const next = await recordSessionFeedback(sessionId, { ...body, request_key: commitmentKey(attempt, body) }); if (identity.current !== sessionId) return; setView(next); setEditing(false); attempt.current = null; await onSaved?.(); }
    catch (reason) { if (identity.current === sessionId) { setError(commitmentFailure(reason)); if (commitmentConflict(reason)) { setConflict(true); setChecked(false); } } }
    finally { if (identity.current === sessionId) setBusy(false); }
  }
  return <details className="session-feedback" open={open} onToggle={event => { const next = event.currentTarget.open; setOpen(next); if (next && !view && !busy) void read(); }}><summary>本人体验与实际投入（可跳过）</summary>
    {busy && !view && <p role="status">正在读取反馈…</p>}{error && <p role="alert">{error}</p>}
    {conflict && <div className="commitment-conflict"><p>已保留你的输入。读取最新反馈后再核对。</p><button className="text-button" type="button" disabled={busy} onClick={() => void read(true)}>读取最新反馈</button>{checked && <button className="text-button" type="button" onClick={() => { setConflict(false); setError(''); attempt.current = null; }}>已核对，继续编辑</button>}{checked && view?.current && <FeedbackSummary value={view.current} />}</div>}
    {!view && error && <button className="text-button" type="button" disabled={busy} onClick={() => void read()}>重新读取反馈</button>}
    {view?.current && !editing && <><FeedbackSummary value={view.current} /><button className="text-button" type="button" onClick={() => { setForm(values(view.current!)); setEditing(true); }}>更正本人反馈</button></>}
    {view?.purged && <p>反馈内容已清除，历史事实保留。</p>}
    {view && editing && !view.purged && <form className="session-feedback-form" onSubmit={event => void save(event)}>
      <div className="commitment-field-grid"><label className="field"><span>这次用于</span><select aria-label="这次用于" value={form.purpose} onChange={event => update('purpose', event.target.value as SessionFeedbackInput['purpose'])}><option value="unknown">尚不确定</option><option value="real" disabled={!!view.known_origin}>实际学习</option><option value="test">演示或测试</option></select></label><label className="field"><span>本人感到</span><select aria-label="本人感到" value={form.progress} onChange={event => update('progress', event.target.value as SessionFeedbackInput['progress'])}><option value="uncertain">还不确定</option><option value="progress">有所进展</option><option value="difficulty">仍有困难</option></select></label></div>
      {view.known_origin && <p className="commitment-muted">这条学习记录已标明用于演示或测试。</p>}
      <fieldset className="commitment-effort"><legend>实际有效投入（分钟，可留空）</legend><div className="commitment-field-grid"><label className="field"><span>至少</span><input type="number" min="0" max="10080" value={form.actual_min_minutes ?? ''} onChange={event => update('actual_min_minutes', event.target.value === '' ? null : Number(event.target.value))} /></label><label className="field"><span>至多</span><input type="number" min="0" max="10080" value={form.actual_max_minutes ?? ''} onChange={event => update('actual_max_minutes', event.target.value === '' ? null : Number(event.target.value))} /></label></div><p className="commitment-muted">只填本人实际投入；不确定就留空。</p></fieldset>
      <details><summary>大小、节奏与方法</summary><div className="commitment-field-grid"><label className="field"><span>任务大小</span><select aria-label="任务大小" value={form.grain} onChange={event => update('grain', event.target.value as SessionFeedbackInput['grain'])}><option value="unknown">未知</option><option value="ok">合适</option><option value="too_large">太大</option><option value="too_small">太小</option></select></label><label className="field"><span>节奏</span><select aria-label="节奏" value={form.pace} onChange={event => update('pace', event.target.value as SessionFeedbackInput['pace'])}><option value="unknown">未知</option><option value="ok">合适</option><option value="too_tight">太紧</option><option value="want_more">想再多做一点</option></select></label><label className="field"><span>方法</span><select aria-label="方法" value={form.method_feedback} onChange={event => update('method_feedback', event.target.value as SessionFeedbackInput['method_feedback'])}><option value="unknown">未知</option><option value="ok">合适</option><option value="unsuitable">不合适</option></select></label><label className="field"><span>这次主要做了</span><select aria-label="这次主要做了" value={form.activity} onChange={event => update('activity', event.target.value as SessionFeedbackInput['activity'])}><option value="learning">学习</option><option value="recall">回忆</option><option value="variation">变式练习</option><option value="transfer">迁移尝试</option></select></label></div></details>
      <details><summary>关联已有产出或作答（可选）</summary>{view.source_choices ? <div className="commitment-field-grid"><label className="field"><span>本次学习产出</span><select aria-label="本次学习产出" value={form.artifact_id ?? ''} onChange={event => { const value = view.source_choices!.artifacts.find(item => item.id === event.target.value); setForm(previous => ({ ...previous, artifact_id: value?.id ?? null, artifact_version: value?.content_version ?? null })); }}><option value="">不关联</option>{view.source_choices.artifacts.map((item, index) => <option key={item.id} value={item.id}>产出 {index + 1} · {new Date(item.created_at).toLocaleString()}</option>)}</select></label><label className="field"><span>本次学习作答</span><select aria-label="本次学习作答" value={form.submission_id ?? ''} onChange={event => update('submission_id', event.target.value || null)}><option value="">不关联</option>{view.source_choices.submissions.map((item, index) => <option key={item.id} value={item.id}>作答 {index + 1} · {new Date(item.created_at).toLocaleString()}</option>)}</select></label><label className="field"><span>同一任务的回访结果</span><select aria-label="同一任务的回访结果" value={form.delayed_attempt_id ?? ''} onChange={event => update('delayed_attempt_id', event.target.value || null)}><option value="">不关联</option>{view.source_choices.delayed_attempts.map((item, index) => <option key={item.id} value={item.id}>回访 {index + 1} · {new Date(item.submitted_at).toLocaleString()}</option>)}</select></label>{form.delayed_attempt_id && <p className="commitment-muted">{view.source_choices.delayed_attempts.find(item => item.id === form.delayed_attempt_id)?.association_label ?? '本人把这个回访结果关联到这次学习'}；不改变它实际发生的时间。</p>}</div> : <p className="commitment-muted">本次可用引用尚未提供，可先保存本人反馈。</p>}</details>
      <label className="field"><span>补充（可选）</span><textarea aria-label="补充（可选）" maxLength={2000} value={form.notes} onChange={event => update('notes', event.target.value)} /></label><div className="commitment-actions"><button className="button button--quiet" type="submit" disabled={busy || conflict}>保存本人反馈</button>{view.current && <button className="text-button" type="button" disabled={busy} onClick={() => setEditing(false)}>取消更正</button>}</div>
    </form>}
    {view && !!view.history.length && <details><summary>反馈历史</summary>{view.history.map(item => <article key={item.revision}><small>{new Date(item.created_at).toLocaleString()}</small><FeedbackSummary value={item} /></article>)}</details>}
    {view && <CommitmentPurge title="清除本人反馈内容" description="清除反馈文字及管理范围内的副本；这份反馈不再参与安排判断。学习与产出事实、反馈更正记录保留。" available={view.can_purge_content ?? view.revision > 0} retryNeeded={view.purge_retry_needed} readStatus={async () => { const [report, latest] = await Promise.all([getSessionFeedbackPurge(sessionId), getSessionFeedback(sessionId)]); setView(latest); return report; }} purge={async key => { const result = await purgeSessionFeedback(sessionId, view.revision, key); setView(result); setEditing(false); return result.purge_report; }} onDone={onSaved} />}
  </details>;
}
