import { expect, test, type APIRequestContext, type Locator, type Page } from '@playwright/test';
import { authorize, checkDefaultTeachingSupport } from './fact-helpers';
import type { CoachSettings, CoachView } from '../src/background-coach-api';

test.setTimeout(90_000);
test.use({ timezoneId: 'Asia/Shanghai' });
const key = (name: string) => `coach-browser:${name}:${Date.now()}:${Math.random().toString(36).slice(2)}`;
async function get<T = any>(request: APIRequestContext, url: string): Promise<T> { const response = await request.get(url); expect(response.ok(), await response.text()).toBeTruthy(); return response.json(); }
async function post(request: APIRequestContext, url: string, data: object): Promise<any> { const response = await request.post(url, { data }); expect(response.ok(), await response.text()).toBeTruthy(); return response.json(); }
async function configure(page: Page, model = 'mock-success') { const response = await page.request.put('/api/ai/provider', { data: { display_name: 'Synthetic coach browser provider', base_url: process.env.NAUTILUS_E2E_MOCK_PROVIDER_URL, model, api_key: 'synthetic-coach-only', enabled: true, request_timeout_seconds: 15 } }); expect(response.ok(), await response.text()).toBeTruthy(); }
async function settings(page: Page, changes: Partial<Omit<CoachSettings, 'revision'>>) { const current = await get<CoachSettings>(page.request, '/api/learning/coach/settings'); const { revision, ...fields } = current; const response = await page.request.put('/api/learning/coach/settings', { data: { ...fields, ...changes, expected_revision: revision, request_key: key('settings') } }); expect(response.ok(), await response.text()).toBeTruthy(); return response.json() as Promise<CoachSettings>; }
const overview = (page: Page, planId?: string) => get<CoachView>(page.request, `/api/learning/coach?scope=${planId ? `plan&plan_id=${planId}` : 'global'}`);
async function calls(page: Page, model = 'mock-success') { const mock = process.env.NAUTILUS_E2E_MOCK_PROVIDER_URL!.replace(/\/v1$/, ''); const value = await get(page.request, `${mock}/__mock__/stats`); return value.requests[`coach:${model}`] ?? 0; }
async function seed(page: Page) {
  const plan = await post(page.request, '/api/learning/plans', { title: '合成教练计划', description: '', goal_id: null, request_key: key('plan') });
  const org = await get(page.request, `/api/learning/plans/${plan.plan_id}/organization`);
  const task = await post(page.request, `/api/learning/plans/${plan.plan_id}/tasks`, { action_title: '合成教练任务', context_key: '合成教练检查', object_description: '合成输入', behavior: '核对合成输入', outcome_context_key: '合成教练检查', outcome_id: null, criterion_id: null, boundaries: '仅合成输入', stop_conditions: '核对后停下', time_budget_minutes: null, expected_revision: org.revision, request_key: key('task') });
  const pathUrl = `/api/learning/plans/${plan.plan_id}/path`, path = await get(page.request, pathUrl);
  const draft = await post(page.request, `${pathUrl}/drafts`, { title: '合成教练路线', nodes: [{ id: 'coach-stage', title: '合成核对阶段', action_ids: [task.action_id], outcome_ids: [] }], edges: [], entry_node_id: 'coach-stage', current_node_id: 'coach-stage', reason: '', intent: 'create', expected_revision: path.revision, expected_organization_revision: path.organization_revision, request_key: key('draft') });
  const preview = await post(page.request, `${pathUrl}/previews`, { draft_id: draft.draft_id });
  await post(page.request, `${pathUrl}/decisions`, { draft_id: draft.draft_id, expected_draft_revision: preview.draft_revision, expected_revision: preview.revision, review_key: preview.review_key, request_key: key('adopt') });
  let state = await get(page.request, '/api/learning/state');
  const session = await post(page.request, '/api/learning/sessions', { delegation_id: task.delegation_id, expected_version: state.actions.find((item: any) => item.id === task.action_id).version, idempotency_key: key('start') });
  state = await get(page.request, '/api/learning/state');
  const sessionId = state.sessions.find((item: any) => item.action_id === task.action_id && item.status === 'running').id;
  const artifact = await post(page.request, '/api/learning/artifacts', { session_id: sessionId, content: '只供合成浏览器检查的产出原文，不进入教练摘要', expected_version: state.actions.find((item: any) => item.id === task.action_id).version, idempotency_key: key('artifact') });
  state = await get(page.request, '/api/learning/state');
  await post(page.request, `/api/learning/sessions/${sessionId}/end`, { disposition: 'interrupted', expected_version: state.actions.find((item: any) => item.id === task.action_id).version, idempotency_key: key('pause') });
  const feedback = await get(page.request, `/api/learning/sessions/${sessionId}/feedback`);
  await post(page.request, `/api/learning/sessions/${sessionId}/feedback`, { actual_min_minutes: null, actual_max_minutes: null, purpose: 'test', grain: 'too_large', pace: 'unknown', method_feedback: 'unknown', progress: 'difficulty', activity: 'learning', artifact_id: artifact.id, artifact_version: 1, submission_id: null, delayed_attempt_id: null, notes: '合成反馈私文，不进入教练摘要', expected_revision: feedback.revision, request_key: key('feedback') });
  return { id: plan.plan_id as string, task, session, sessionId };
}
async function openPlan(page: Page, id: string) { await page.goto(`/?view=plans&plan=${id}&plan_view=tasks`); const panel = page.getByRole('region', { name: '计划后台教练', exact: true }); await expect(panel.getByRole('button', { name: '手动复盘', exact: true })).toBeEnabled(); return panel; }
async function finished(page: Page, planId?: string) { await expect.poll(async () => (await overview(page, planId)).latest_run?.status, { timeout: 20_000 }).toBe('succeeded'); }
async function expandCoach(panel: Locator) { await expect(panel.locator('.background-coach__list [data-coach-candidate]').first()).toBeVisible(); const button = panel.getByRole('button', { name: /^查看其余建议/ }); if (await button.count()) await button.click(); }
async function screenshotCoach(page: Page, panel: Locator, path: string, width: number) {
  await page.setViewportSize({ width, height: 900 });
  await page.locator('.v6-main-column').evaluate(element => { element.scrollTop = 0; });
  const bounds = await panel.evaluate(element => { const box = element.getBoundingClientRect(); return { top: box.top, height: box.height }; });
  await page.setViewportSize({ width, height: Math.max(900, Math.ceil(bounds.top + bounds.height + 160)) });
  await page.locator('.v6-main-column').evaluate(element => { element.scrollTop = 0; });
  await page.screenshot({ path });
}

test('manual plan review preserves provenance and tasks through reject, ignore, undo and accept; mobile remains usable', async ({ page }) => {
  await authorize(page); await configure(page); await settings(page, { enabled: false }); const plan = await seed(page); const before = await calls(page); const prior = await get(page.request, '/api/learning/state');
  let panel = await openPlan(page, plan.id); await page.reload(); panel = page.getByRole('region', { name: '计划后台教练', exact: true }); await expect(panel.getByRole('button', { name: '手动复盘', exact: true })).toBeEnabled(); expect(await calls(page)).toBe(before);
  await panel.getByRole('button', { name: '手动复盘', exact: true }).click(); await finished(page, plan.id); await expect(panel.locator('[data-coach-candidate]')).not.toHaveCount(0); expect(await calls(page)).toBe(before + 1);
  const snapshot = await overview(page, plan.id); const taskCandidate = snapshot.candidates.find(item => item.target?.kind === 'task')!; expect(taskCandidate).toBeTruthy();
  await expect(panel.locator('[data-coach-candidate]')).toHaveCount(1); await expect(panel).toContainText(`${snapshot.candidates.length} 条待处理建议`); await expect(page.getByRole('navigation', { name: '计划视图', exact: true })).toBeInViewport();
  await screenshotCoach(page, panel, '/tmp/nautilus-coach-plan-desktop.png', 1280); await screenshotCoach(page, panel, '/tmp/nautilus-coach-plan-390.png', 390); await screenshotCoach(page, panel, '/tmp/nautilus-coach-plan-320.png', 320); await page.setViewportSize({ width: 1280, height: 900 });
  const firstPending = snapshot.candidates[0], nextPending = snapshot.candidates[1]; await panel.locator(`[data-coach-candidate="${firstPending.id}"]`).getByRole('button', { name: '暂不处理', exact: true }).click(); await expect(panel.locator(`.background-coach__list [data-coach-candidate="${nextPending.id}"]`)).toBeVisible(); await expect(panel.locator('.background-coach__list [data-coach-candidate]')).toHaveCount(1); expect(await calls(page)).toBe(before + 1);
  await panel.getByText('处理记录与复盘设置', { exact: true }).click(); await panel.locator(`[data-coach-candidate="${firstPending.id}"]`).getByRole('button', { name: '撤销处理', exact: true }).click(); await expect(panel.locator(`.background-coach__list [data-coach-candidate="${firstPending.id}"]`)).toBeVisible(); await panel.getByText('处理记录与复盘设置', { exact: true }).click();
  await expandCoach(panel); await expect(panel.locator('[data-coach-candidate]')).toHaveCount(snapshot.candidates.length); expect(await calls(page)).toBe(before + 1); await panel.getByRole('button', { name: '收起其余建议', exact: true }).click(); await expect(panel.locator('[data-coach-candidate]')).toHaveCount(1); expect(await calls(page)).toBe(before + 1); await expandCoach(panel);
  const card = () => panel.locator(`[data-coach-candidate="${taskCandidate.id}"]`);
  await expect(card().locator('.background-coach__basis > ul').first()).not.toBeVisible(); await card().getByText('依据与仍未知的内容', { exact: true }).click(); await expect(card().locator('.background-coach__basis a').first()).toBeVisible();
  await card().getByRole('button', { name: '拒绝', exact: true }).click(); await panel.getByText('处理记录与复盘设置', { exact: true }).click(); await expect(card()).toContainText('已拒绝'); await card().getByRole('button', { name: '撤销处理', exact: true }).click();
  await card().getByRole('button', { name: '暂不处理', exact: true }).click(); await expect(card()).toContainText('暂不处理'); await card().getByRole('button', { name: '撤销处理', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.setViewportSize({ width: 320, height: 760 }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.setViewportSize({ width: 320, height: 760 });
  await card().getByRole('button', { name: '接受并查看', exact: true }).click(); await expect(page).toHaveURL(new RegExp(`action=${plan.task.action_id}`)); await expect(page.getByRole('complementary', { name: '教练建议来源', exact: true })).toContainText(taskCandidate.title!); await expect(page.locator('.learning-plan-task.is-coach-target')).toContainText('合成教练任务');
  const after = await get(page.request, '/api/learning/state'); expect(after.sessions.length).toBe(prior.sessions.length); expect(after.actions.map((item: any) => [item.id, item.status])).toEqual(prior.actions.map((item: any) => [item.id, item.status]));
  await page.getByRole('button', { name: '回看原复盘与依据', exact: true }).click(); const detail = page.getByRole('dialog', { name: '教练复盘详情', exact: true }); await expect(detail).toContainText(taskCandidate.title!); await page.keyboard.press('Escape'); await expect(detail).not.toBeVisible(); await expect(page.getByRole('button', { name: '回看原复盘与依据', exact: true })).toBeFocused();
  await page.reload(); expect(await calls(page)).toBe(before + 1);
  const otherPlan = await post(page.request, '/api/learning/plans', { title: '合成另一个计划', description: '', goal_id: null, request_key: key('other-plan') }); await page.reload();
  const delayedCandidate = snapshot.candidates.find(item => item.target?.kind === 'path_review')!; expect(delayedCandidate).toBeTruthy();
  let releaseDecision!: () => void, decisionSeen!: () => void; const decisionGate = new Promise<void>(resolve => { releaseDecision = resolve; }), decisionCaptured = new Promise<void>(resolve => { decisionSeen = resolve; });
  await page.route(`**/api/learning/coach/candidates/${delayedCandidate.id}/decisions`, async route => { const response = await route.fetch(); decisionSeen(); await decisionGate; await route.fulfill({ response }); });
  await expandCoach(page.getByRole('region', { name: '计划后台教练', exact: true })); await page.getByRole('region', { name: '计划后台教练', exact: true }).locator(`[data-coach-candidate="${delayedCandidate.id}"]`).getByRole('button', { name: '接受并查看', exact: true }).click(); await decisionCaptured;
  await page.getByRole('navigation', { name: '计划列表', exact: true }).getByRole('button', { name: /合成另一个计划/ }).click(); await expect(page).toHaveURL(new RegExp(`plan=${otherPlan.plan_id}`)); releaseDecision();
  await expect.poll(async () => (await get(page.request, `/api/learning/coach/candidates/${delayedCandidate.id}`)).status).toBe('accepted'); await expect(page).toHaveURL(new RegExp(`plan=${otherPlan.plan_id}`));
});

test('settings persist timezone and limits; automatic return is one batch across refresh and global view', async ({ page }) => {
  await authorize(page); await configure(page); await settings(page, { enabled: false, max_calls_per_session: 1, max_calls_per_day: 3, cooldown_minutes: 30, timezone: 'UTC' }); const plan = await seed(page); const before = await calls(page);
  await page.goto('/?view=home'); await page.getByRole('button', { name: '设置', exact: true }).click(); const dialog = page.getByRole('dialog', { name: '设置', exact: true }), coach = dialog.getByRole('region', { name: '后台教练设置', exact: true });
  await coach.getByLabel('自动复盘', { exact: true }).check(); await coach.getByText('调用限额与时区', { exact: true }).click(); await coach.getByLabel('每天自动复盘最多（次）', { exact: true }).fill('4'); await coach.getByLabel('自动复盘间隔至少（分钟）', { exact: true }).fill('45'); await coach.getByRole('button', { name: /使用本机时区/ }).click(); const timezone = await page.evaluate(() => Intl.DateTimeFormat().resolvedOptions().timeZone); await coach.getByRole('button', { name: '保存教练设置', exact: true }).click(); await expect(coach).toContainText('自动复盘设置已保存');
  const saved = await get<CoachSettings>(page.request, '/api/learning/coach/settings'); expect(saved).toMatchObject({ enabled: true, max_calls_per_day: 4, cooldown_minutes: 45, timezone }); await dialog.getByRole('button', { name: '关闭设置', exact: true }).click();
  await openPlan(page, plan.id); await finished(page, plan.id); expect(await calls(page)).toBe(before + 1); await page.reload(); await expect(page.getByRole('region', { name: '计划后台教练', exact: true }).locator('[data-coach-candidate]')).not.toHaveCount(0); expect(await calls(page)).toBe(before + 1);
  await page.goto('/?view=home'); const home = page.getByRole('region', { name: '后台教练', exact: true }); await expect(home).toBeVisible(); await expect(home.getByRole('button', { name: '手动复盘', exact: true })).toBeEnabled(); expect(await calls(page)).toBe(before + 1);
  await settings(page, { enabled: false, timezone: 'UTC' }); await page.getByRole('button', { name: '设置', exact: true }).click(); const savedCoach = page.getByRole('region', { name: '后台教练设置', exact: true }); await savedCoach.getByLabel('自动复盘', { exact: true }).check(); await expect(savedCoach).toContainText('待保存时区：UTC'); await savedCoach.getByRole('button', { name: '保存教练设置', exact: true }).click(); expect((await get<CoachSettings>(page.request, '/api/learning/coach/settings')).timezone).toBe('UTC'); await settings(page, { enabled: false });
});

test('cancel and failure survive refresh; retry explicitly starts a new attempt and purge retains learning facts', async ({ page }) => {
  await authorize(page); await settings(page, { enabled: false }); await configure(page, 'mock-slow'); const plan = await seed(page); const prior = await get(page.request, '/api/learning/state');
  let panel = await openPlan(page, plan.id);
  let releaseView!: () => void, viewSeen!: () => void, heldView = false; const viewGate = new Promise<void>(resolve => { releaseView = resolve; }), viewCaptured = new Promise<void>(resolve => { viewSeen = resolve; });
  await page.route('**/api/learning/coach?*', async route => { if (heldView || !route.request().url().includes(plan.id)) return route.continue(); heldView = true; const response = await route.fetch(); viewSeen(); await viewGate; await route.fulfill({ response }); });
  await panel.getByRole('button', { name: '刷新', exact: true }).click(); await viewCaptured; await panel.getByRole('button', { name: '手动复盘', exact: true }).click(); await expect(panel.getByRole('button', { name: '取消复盘', exact: true })).toBeVisible(); releaseView();
  await expect(panel.getByRole('button', { name: '取消复盘', exact: true })).toBeVisible(); await page.unroute('**/api/learning/coach?*'); await page.reload(); panel = page.getByRole('region', { name: '计划后台教练', exact: true }); await expect(panel.getByRole('button', { name: '取消复盘', exact: true })).toBeVisible(); const activeId = (await overview(page, plan.id)).active_run!.id;
  let releasePoll!: () => void, pollSeen!: () => void, heldPoll = false; const pollGate = new Promise<void>(resolve => { releasePoll = resolve; }), pollCaptured = new Promise<void>(resolve => { pollSeen = resolve; });
  await page.route(`**/api/learning/coach/checks/${activeId}`, async route => { if (heldPoll || route.request().method() !== 'GET') return route.continue(); heldPoll = true; const response = await route.fetch(); const body = await response.json(); expect(['queued', 'running']).toContain(body.run.status); pollSeen(); await pollGate; await route.fulfill({ response, json: body }); });
  await pollCaptured; await panel.getByRole('button', { name: '取消复盘', exact: true }).click(); await expect(panel).toContainText('已取消复盘'); releasePoll(); await expect(panel.getByRole('button', { name: '取消复盘', exact: true })).toHaveCount(0); await page.unroute(`**/api/learning/coach/checks/${activeId}`);
  const canceled = (await overview(page, plan.id)).latest_run!; await configure(page, 'mock-error'); const retryCall = page.waitForResponse(response => response.url().endsWith('/api/learning/coach/checks') && response.request().method() === 'POST'); await panel.getByRole('button', { name: '重试这次复盘', exact: true }).click(); const retryResponse = await retryCall; expect(retryResponse.ok(), await retryResponse.text()).toBeTruthy(); const acceptedRetry = await retryResponse.json(); expect(acceptedRetry.run?.id, acceptedRetry.reason ?? 'explicit retry has a new run').toBeTruthy(); expect(acceptedRetry.run.id).not.toBe(canceled.id); await expect.poll(async () => (await overview(page, plan.id)).latest_run?.status).toBe('failed'); const failed = (await overview(page, plan.id)).latest_run!; expect(failed.id).not.toBe(canceled.id); const errors = await calls(page, 'mock-error'); await page.reload(); panel = page.getByRole('region', { name: '计划后台教练', exact: true }); await expect(panel.getByRole('button', { name: '重试这次复盘', exact: true })).toBeVisible(); expect(await calls(page, 'mock-error')).toBe(errors);
  await configure(page); await panel.getByRole('button', { name: '重试这次复盘', exact: true }).click(); await finished(page, plan.id); const success = (await overview(page, plan.id)).latest_run!; expect(success.id).not.toBe(failed.id); await panel.getByText('处理记录与复盘设置', { exact: true }).click(); await panel.getByRole('button', { name: '最近复盘详情', exact: true }).click(); const detail = page.getByRole('dialog', { name: '教练复盘详情', exact: true }); page.once('dialog', event => event.accept()); await detail.getByRole('button', { name: '清除这次复盘内容', exact: true }).click(); await expect(detail).toContainText('复盘内容已清除');
  const after = await get(page.request, '/api/learning/state'); expect(after.sessions.length).toBe(prior.sessions.length); expect(after.artifacts.map((item: any) => [item.id, item.content])).toEqual(prior.artifacts.map((item: any) => [item.id, item.content]));
});

test('same-answer immediate entrance exits the current learning room UI without ending or moving its session', async ({ page }) => {
  await authorize(page); await settings(page, { enabled: false }); await configure(page); await checkDefaultTeachingSupport(page); const plan = await seed(page); const panel = await openPlan(page, plan.id);
  const coachCalls = await calls(page); await expect(panel).toBeVisible();
  await page.locator(`[data-task-id="${plan.task.action_id}"]`).getByRole('button', { name: /开始学习|继续学习/ }).click();
  const input = page.getByLabel('输入学习问题', { exact: true }); await expect(input).toBeEnabled();
  const accepted = page.waitForResponse(response => /\/api\/ai\/conversations\/[^/]+\/messages$/.test(response.url()) && response.request().method() === 'POST');
  await input.fill('请单独安排合成教练即时工作'); await input.press('Enter'); const response = await accepted; expect(response.ok(), await response.text()).toBeTruthy(); const { run } = await response.json();
  await expect.poll(async () => (await get(page.request, `/api/ai/conversations/${run.conversation_id}`)).active_run, { timeout: 20_000 }).toBeNull();
  const immediate = page.getByRole('complementary', { name: '当前学习需要核对的事项', exact: true }); await expect(immediate).toBeVisible();
  expect(await page.evaluate(() => JSON.parse(sessionStorage.getItem('nautilus.ai.learning-room')!).open)).toBe(true);
  const before = await get(page.request, '/api/learning/state'); const running = before.sessions.find((item: any) => item.action_id === plan.task.action_id && item.status === 'running'); expect(running).toBeTruthy();
  await immediate.getByRole('link').click(); await expect(page).toHaveURL(/view=plans/); await expect(page.getByRole('dialog', { name: /添加.*任务|创建.*任务|新建.*任务/ })).toBeVisible();
  expect(await page.evaluate(() => JSON.parse(sessionStorage.getItem('nautilus.ai.learning-room')!).open)).toBe(false);
  const after = await get(page.request, '/api/learning/state'); expect(after.sessions.map((item: any) => [item.id, item.status])).toEqual(before.sessions.map((item: any) => [item.id, item.status])); expect(await calls(page)).toBe(coachCalls);
  await page.screenshot({ path: '/tmp/nautilus-coach-immediate-new-task.png', fullPage: true });
  // Release only the synthetic fixture, after proving that navigation kept it running.
  await post(page.request, `/api/learning/sessions/${running.id}/end`, { disposition: 'interrupted', expected_version: after.actions.find((item: any) => item.id === plan.task.action_id).version, idempotency_key: key('fixture-stop') });
});

async function permissionCandidate(page: Page, plan: Awaited<ReturnType<typeof seed>>) {
  const panel = await openPlan(page, plan.id); await panel.getByRole('button', { name: '手动复盘', exact: true }).click(); await finished(page, plan.id);
  const candidate = (await overview(page, plan.id)).candidates.find(item => item.target?.kind === 'permission_review'); expect(candidate?.target?.permission_request).toBeTruthy();
  await expandCoach(panel); await panel.locator(`[data-coach-candidate="${candidate!.id}"]`).getByRole('button', { name: '接受并查看', exact: true }).click(); const permission = page.getByRole('region', { name: '本次教练读取申请', exact: true }); await expect(permission).toBeVisible(); await expect(permission).toContainText(candidate!.target!.permission_request!.purpose); await expect(permission).toContainText('最多 3 份'); await expect(permission).toContainText('5 分钟'); return { candidate: candidate!, permission };
}

test('a permission suggestion requires separate request, approval and one explicit bounded review; grant replay does not charge again', async ({ page }) => {
  await authorize(page); await settings(page, { enabled: false }); await configure(page); const plan = await seed(page); const prior = await get(page.request, '/api/learning/state'); const { candidate, permission } = await permissionCandidate(page, plan); const before = await calls(page);
  let requests = await get(page.request, '/api/learning/agent/permission-requests'); expect(requests.some((item: any) => item.request_key === candidate.target!.permission_request!.request_key)).toBe(false);
  await expect(permission.getByRole('button', { name: '用本次授权继续复盘', exact: true })).toHaveCount(0); await permission.getByRole('button', { name: '发起本次读取申请', exact: true }).click(); await expect(permission.getByRole('button', { name: '批准本次读取', exact: true })).toBeVisible(); expect(await calls(page)).toBe(before);
  requests = await get(page.request, '/api/learning/agent/permission-requests'); const request = requests.find((item: any) => item.request_key === candidate.target!.permission_request!.request_key); expect(request).toMatchObject({ purpose: candidate.target!.permission_request!.purpose, target_id: plan.task.action_id, content_granularity: 'full_text', ttl_seconds: 300, status: 'pending' });
  await permission.screenshot({ path: '/tmp/nautilus-coach-permission-request.png' }); await permission.getByRole('button', { name: '批准本次读取', exact: true }).click(); await expect(permission.getByRole('button', { name: '用本次授权继续复盘', exact: true })).toBeVisible(); expect(await calls(page)).toBe(before);
  await permission.screenshot({ path: '/tmp/nautilus-coach-permission-approved.png' }); await permission.getByRole('button', { name: '用本次授权继续复盘', exact: true }).click(); await expect.poll(async () => { const value = await overview(page, plan.id); return value.latest_run?.id !== candidate.run_id && value.latest_run?.status === 'succeeded'; }, { timeout: 20_000 }).toBe(true); expect(await calls(page)).toBe(before + 1);
  const first = (await overview(page, plan.id)).latest_run!; const detail = await get(page.request, `/api/learning/coach/checks/${first.id}`); expect(detail.inputs.authorization).toMatchObject({ request_id: request.id, candidate_id: candidate.id, action_id: plan.task.action_id, content_granularity: 'full_text' }); expect(detail.inputs.authorization.artifacts).toHaveLength(1); expect(detail.inputs.authorization.artifacts[0].content).toBe('只供合成浏览器检查的产出原文，不进入教练摘要'); expect(detail.inputs.authorization.artifacts[0].version).toBe(1);
  await page.reload(); const restored = page.getByRole('region', { name: '本次教练读取申请', exact: true }); await restored.getByRole('button', { name: '用本次授权继续复盘', exact: true }).click(); await expect(restored.getByRole('button', { name: '查看本次授权复盘', exact: true })).toBeVisible(); expect((await overview(page, plan.id)).latest_run!.id).toBe(first.id); expect(await calls(page)).toBe(before + 1);
  const after = await get(page.request, '/api/learning/state'); expect(after.sessions.map((item: any) => [item.id, item.status])).toEqual(prior.sessions.map((item: any) => [item.id, item.status]));
  await restored.getByRole('button', { name: '撤销本次授权', exact: true }).click(); await expect(restored).toContainText('已撤销'); await expect(restored.getByRole('button', { name: '用本次授权继续复盘', exact: true })).toHaveCount(0); expect(await calls(page)).toBe(before + 1);
  const oldGrant = await page.request.post('/api/learning/coach/checks', { data: { scope: candidate.scope, ...(candidate.scope === 'plan' ? { plan_id: candidate.plan_id } : {}), trigger: 'manual', permission_candidate_id: candidate.id, permission_request_id: request.id, request_key: key('revoked-grant') } });
  if (oldGrant.ok()) expect((await oldGrant.json()).run?.id).toBe(first.id); expect(await calls(page)).toBe(before + 1);
  await restored.getByRole('button', { name: '重新发起本次读取申请', exact: true }).click(); await restored.getByRole('button', { name: '批准本次读取', exact: true }).click(); const renewed = await get(page.request, '/api/learning/agent/permission-requests'); const newRequest = renewed.find((item: any) => item.target_id === plan.task.action_id && item.grant_status === 'active'); expect(newRequest.id).not.toBe(request.id); expect(newRequest.request_key).not.toBe(request.request_key); expect(await calls(page)).toBe(before + 1);
  await restored.getByRole('button', { name: '用本次授权继续复盘', exact: true }).click(); await expect.poll(async () => { const value = await overview(page, plan.id); return value.latest_run?.id !== first.id && value.latest_run?.status === 'succeeded'; }, { timeout: 20_000 }).toBe(true); expect(await calls(page)).toBe(before + 2);
});

test('refusing a permission suggestion keeps the task available; revoking a sent grant rejects the late result', async ({ page }) => {
  await authorize(page); await settings(page, { enabled: false }); await configure(page); const refusedPlan = await seed(page); let { candidate, permission } = await permissionCandidate(page, refusedPlan); const beforeRefusal = await calls(page);
  await permission.getByRole('button', { name: '发起本次读取申请', exact: true }).click(); await permission.getByRole('button', { name: '拒绝本次读取', exact: true }).click(); await expect(permission).toContainText('已拒绝'); await permission.getByRole('link', { name: '回到原任务核对或补充摘要', exact: true }).click(); await expect(page.locator('.learning-plan-task.is-coach-target')).toContainText('合成教练任务'); expect(await calls(page)).toBe(beforeRefusal);
  const plan = await seed(page); ({ candidate, permission } = await permissionCandidate(page, plan)); await permission.getByRole('button', { name: '发起本次读取申请', exact: true }).click(); await permission.getByRole('button', { name: '批准本次读取', exact: true }).click(); await configure(page, 'mock-slow'); await permission.getByRole('button', { name: '用本次授权继续复盘', exact: true }).click();
  const run = (await overview(page, plan.id)).active_run!; expect(run).toBeTruthy(); const requests = await get(page.request, '/api/learning/agent/permission-requests'); const request = requests.find((item: any) => item.request_key === candidate.target!.permission_request!.request_key);
  await post(page.request, `/api/learning/agent/permission-requests/${request.id}/revoke`, { reason: '合成其他页面撤回本次授权' }); await expect.poll(async () => (await get(page.request, `/api/learning/coach/checks/${run.id}`)).run.status, { timeout: 20_000 }).toBe('failed'); const detail = await get(page.request, `/api/learning/coach/checks/${run.id}`); expect(detail.candidates).toHaveLength(0);
  await permission.getByRole('button', { name: '刷新本次权限', exact: true }).click(); await expect(permission).toContainText('已撤销'); await expect(permission.getByRole('button', { name: '用本次授权继续复盘', exact: true })).toHaveCount(0); await configure(page);
});

test('accepting a specific evidence suggestion opens the existing claim controls and preserves formal review until user action', async ({ page }) => {
  await authorize(page); await settings(page, { enabled: false }); await configure(page, 'mock-evidence');
  let state = await get(page.request, '/api/learning/state'); const standard = state.standards.find((item: any) => item.context_key === 'python-regex-basics' && item.review_status === 'approved'); expect(standard).toBeTruthy();
  const action = await post(page.request, '/api/learning/actions', { title: '合成正则复核任务', context_key: 'python-regex-basics', idempotency_key: key('evidence-task') });
  const delegation = await post(page.request, '/api/learning/delegations', { action_id: action.id, outcome_id: standard.outcome_id, criterion_id: standard.id, boundaries: '只核对基础正则', stop_conditions: '检查后停下', time_budget_minutes: null, expected_version: action.version, idempotency_key: key('evidence-delegation') });
  const session = await post(page.request, '/api/learning/sessions', { delegation_id: delegation.id, expected_version: delegation.version, idempotency_key: key('evidence-session') });
  const artifact = await post(page.request, '/api/learning/artifacts', { session_id: session.id, content: 'regex: ^Nautilus\\d+$\nsample: Nautilus42', expected_version: session.version, idempotency_key: key('evidence-artifact') });
  const analysis = await post(page.request, `/api/learning/artifacts/${artifact.id}/analysis`, { request_key: key('evidence-analysis') }); expect(analysis.claims.length).toBeGreaterThan(0); const claimIds = new Set(analysis.claims.filter((item: any) => item.status === 'candidate').map((item: any) => item.id)); expect(claimIds.size).toBeGreaterThan(0);
  state = await get(page.request, '/api/learning/state'); await post(page.request, `/api/learning/sessions/${session.id}/end`, { disposition: 'interrupted', expected_version: state.actions.find((item: any) => item.id === action.id).version, idempotency_key: key('evidence-stop') }); await configure(page);
  await page.goto('/?view=home'); const panel = page.getByRole('region', { name: '后台教练', exact: true }); await panel.getByRole('button', { name: '手动复盘', exact: true }).click(); await finished(page);
  const candidate = (await overview(page)).candidates.find(item => item.target?.kind === 'evidence_review' && claimIds.has(item.target.object_id)); expect(candidate).toBeTruthy(); const claim = analysis.claims.find((item: any) => item.id === candidate!.target!.object_id);
  const before = await get(page.request, '/api/learning/state'); await expandCoach(panel); await panel.locator(`[data-coach-candidate="${candidate!.id}"]`).getByRole('button', { name: '接受并查看', exact: true }).click(); await expect(page).toHaveURL(new RegExp(`review_claim=${claim.id}`));
  const controls = page.locator(`#coach-claim-${claim.id}`); await expect(controls.getByRole('button', { name: '采纳', exact: true })).toBeEnabled(); await expect(controls.getByRole('button', { name: '质疑', exact: true })).toBeEnabled(); await expect(controls).toBeFocused();
  const after = await get(page.request, '/api/learning/state'); expect(after.evidence_claims.find((item: any) => item.id === claim.id).status).toBe('candidate'); expect(after.review_actions.length).toBe(before.review_actions.length); expect(after.sessions.map((item: any) => [item.id, item.status])).toEqual(before.sessions.map((item: any) => [item.id, item.status]));
  await page.screenshot({ path: '/tmp/nautilus-coach-evidence-claim.png' });
});
