import { expect, test } from '@playwright/test';
import { authorize } from './fact-helpers';
import { execFileSync } from 'node:child_process';
import { join } from 'node:path';

test('fixed regex follow-up completes both attempts and compares recorded conditions', async ({ page }) => {
  await authorize(page);
  const state = await (await page.request.get('/api/learning/state')).json();
  const standard = state.standards.find((item: { id: string }) => item.id === 'python-regex-basics-v1') ?? state.standards[0];
  const suffix = crypto.randomUUID();
  const actionResponse = await page.request.post('/api/learning/actions', { data: { title: '合成正则回访行动', context_key: 'python-regex-basics', idempotency_key: `delayed-action-${suffix}` } });
  expect(actionResponse.ok()).toBeTruthy();
  const action = await actionResponse.json();
  const delegationResponse = await page.request.post('/api/learning/delegations', { data: { action_id: action.id, outcome_id: standard.outcome_id, criterion_id: standard.id, boundaries: '合成回访', stop_conditions: '完成回访', time_budget_minutes: 30, expected_version: 1, idempotency_key: `delayed-delegation-${suffix}` } });
  expect(delegationResponse.ok()).toBeTruthy();
  const delegation = await delegationResponse.json();
  const sessionResponse = await page.request.post('/api/learning/sessions', { data: { delegation_id: delegation.id, expected_version: 2, idempotency_key: `delayed-session-${suffix}` } });
  expect(sessionResponse.ok()).toBeTruthy();
  const session = await sessionResponse.json();
  const artifactResponse = await page.request.post('/api/learning/artifacts', { data: { session_id: session.id, content: 're.fullmatch("[A-Z]{2}[0-9]{2}", "AB12")', expected_version: 3, idempotency_key: `delayed-artifact-${suffix}` } });
  expect(artifactResponse.ok()).toBeTruthy();

  await page.goto(`/?view=records&outcome=${standard.outcome_id}`);
  const panel = page.getByRole('region', { name: '窄领域延迟回访' });
  await expect(panel.getByRole('button', { name: '开始初次记录' })).toBeVisible();
  await panel.getByRole('button', { name: '开始初次记录' }).click();
  const form = panel.getByRole('region', { name: '初次作答' });
  await expect(form.locator('fieldset')).toHaveCount(8);
  await form.locator('fieldset').first().getByLabel('是').check();
  const draftResponse = page.waitForResponse(response => response.url().endsWith('/draft') && response.request().method() === 'PUT');
  await form.getByRole('button', { name: '保存草稿' }).click();
  expect((await draftResponse).ok()).toBe(true);
  await page.reload();
  await panel.getByRole('button', { name: /初次记录 ·/ }).click();
  await expect(panel.getByRole('region', { name: '初次作答' }).locator('fieldset').first().getByLabel('是')).toBeChecked();
  const expected = [true, false, false, false, true, true, false, false];
  for (const [index, answer] of expected.entries()) await panel.getByRole('region', { name: '初次作答' }).locator('fieldset').nth(index).getByLabel(answer ? '是' : '否').check();
  await panel.getByRole('button', { name: '提交全部 8 项' }).click();
  await expect(panel.getByRole('button', { name: '运行确定性检查' })).toBeVisible();
  await panel.getByRole('button', { name: '查看已保存答案', exact: true }).click();
  await expect(panel.locator('.delayed-detail__reveal li')).toHaveCount(8);
  await expect(panel.locator('.delayed-detail__reveal')).toContainText('检查结果尚不可用');
  await panel.getByRole('button', { name: '运行确定性检查' }).click();
  await expect(panel.getByText('检查已完成')).toBeVisible();
  await panel.getByRole('button', { name: '查看已保存答案与检查结果' }).click();
  await expect(panel.getByText('8/8 项正确')).toBeVisible();
  await panel.getByRole('button', { name: '安排回访' }).click();
  await expect(panel.getByText('等待回访', { exact: true }).first()).toBeVisible();
  await expect(panel.getByText('8/8 项正确')).toHaveCount(0);
  page.once('dialog', dialog => void dialog.accept());
  await panel.getByRole('button', { name: '查看已保存答案与检查结果' }).click();
  await expect(panel.getByText('8/8 项正确')).toBeVisible();
  const series = (await (await page.request.get(`/api/learning/outcomes/${standard.outcome_id}/delayed-follow-ups`)).json()).items[0];
  expect(series.id).toBeTruthy();
  await page.getByRole('button', { name: '学习首页', exact: true }).first().click();
  const home = page.getByRole('region', { name: '到期回访' });
  await expect(home.getByRole('button', { name: /等待回访/ })).toBeVisible();
  await home.getByRole('button', { name: /等待回访/ }).click();
  await home.getByRole('button', { name: '跳过这次回访' }).click();
  await expect(home.getByText('已跳过', { exact: true })).toBeVisible();
  await home.getByRole('button', { name: '保存改期' }).click();
  await expect(home.getByText('等待回访', { exact: true })).toBeVisible();

  // Synthetic due-time fixture only: the E2E launcher creates and later deletes this /tmp database.
  const dataDir = process.env.NAUTILUS_E2E_DATA_DIR;
  if (!dataDir?.startsWith('/tmp/nautilus-playwright.')) throw new Error('Refusing to adjust a non-isolated database');
  const script = 'import sqlite3,sys,datetime\np=sys.argv[1]; i=sys.argv[2]\nc=sqlite3.connect(p)\nnow=datetime.datetime.now(datetime.timezone.utc)\nc.execute("UPDATE learning_delayed_attempt SET submitted_at=? WHERE follow_up_id=? AND phase=\'initial\'", ((now-datetime.timedelta(days=3)).isoformat(),i))\nc.execute("UPDATE learning_delayed_follow_up SET due_at=? WHERE id=?", ((now-datetime.timedelta(minutes=1)).isoformat(),i))\nc.commit();c.close()';
  execFileSync('python3', ['-c', script, join(dataDir, 'learning.sqlite3'), series.id]);
  await home.getByRole('button', { name: '刷新状态' }).click();
  await expect(home.getByRole('button', { name: '开始回访' })).toBeVisible();
  await home.getByRole('button', { name: '开始回访' }).click();
  const followup = home.getByRole('region', { name: '回访作答' });
  await expect(followup.locator('fieldset')).toHaveCount(8);
  await expect(home.getByText('8/8 项正确')).toHaveCount(0);
  for (const [index, answer] of expected.entries()) await followup.locator('fieldset').nth(index).getByLabel(answer ? '是' : '否').check();
  await followup.getByRole('button', { name: '提交全部 8 项' }).click();
  await home.getByRole('button', { name: '运行确定性检查' }).click();
  await expect(home.getByText('两次记录比较')).toBeVisible();
  await expect(home.getByText('达到最小间隔')).toBeVisible();
  const completed = await (await page.request.get(`/api/learning/delayed-follow-ups/${series.id}`)).json();
  expect(completed.status).toBe('completed');
  expect(completed.comparison.interval_met).toBe(true);
  expect(completed.attempts[1].condition.observed_views.some((view: { after_arranging: boolean; provided_at: string; displayed_at: string }) => view.after_arranging && view.provided_at && view.displayed_at)).toBe(true);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: '/tmp/nautilus-delayed-comparison-mobile.png', fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.reload();
  await page.goto(`/?view=records&outcome=${standard.outcome_id}`);
  await panel.getByRole('button', { name: /回访已提交 ·/ }).click();
  await expect(panel.getByText('两次记录比较')).toBeVisible();
});
