import { expect, test } from '@playwright/test';
import { authorize } from './fact-helpers';

test('opt-in persistent diagnostic panel, filtering, collapse, clearing and disable', async ({ page }) => {
  await authorize(page);
  await expect(page.getByRole('button', { name: '日志', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: '设置', exact: true }).click();
  const settings = page.getByRole('dialog', { name: '设置', exact: true });
  await settings.getByText('高级设置', { exact: true }).click();
  await expect(settings.getByLabel('开启诊断日志')).not.toBeChecked();
  await settings.getByLabel('开启诊断日志').click();
  await expect(settings.getByLabel('开启诊断日志')).toBeChecked();
  await settings.getByRole('button', { name: '打开日志窗口' }).click();
  await expect(settings).toHaveCount(0);
  const panel = page.getByRole('dialog', { name: '诊断日志', exact: true });
  await expect(panel).toBeVisible();
  const original = (await panel.boundingBox())!;
  const title = panel.locator('.diagnostic-titlebar strong');
  const titleBounds = (await title.boundingBox())!;
  await page.mouse.move(titleBounds.x + 20, titleBounds.y + 8);
  await page.mouse.down();
  await page.mouse.move(titleBounds.x + 80, titleBounds.y + 48, { steps: 5 });
  await page.mouse.up();
  const moved = (await panel.boundingBox())!;
  expect(moved.x).toBeCloseTo(original.x + 60, 0);
  expect(moved.y).toBeCloseTo(original.y + 40, 0);
  const handle = (await panel.getByRole('slider', { name: '调整日志窗口大小' }).boundingBox())!;
  await page.mouse.move(handle.x + 12, handle.y + 12);
  await page.mouse.down();
  await page.mouse.move(handle.x - 88, handle.y - 48, { steps: 5 });
  await page.mouse.up();
  const resized = (await panel.boundingBox())!;
  expect(resized.width).toBeCloseTo(moved.width - 100, 0);
  expect(resized.height).toBeCloseTo(moved.height - 60, 0);
  await panel.getByRole('button', { name: '最大化日志' }).click();
  expect(await panel.boundingBox()).toEqual({ x: 0, y: 0, width: 1280, height: 720 });
  await panel.getByRole('button', { name: '还原窗口' }).click();
  expect(await panel.boundingBox()).toEqual(resized);
  await panel.getByRole('button', { name: '最小化日志' }).click();
  await expect(panel).toHaveCount(0);
  await expect(page.getByRole('heading', { name: '学习首页', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '日志', exact: true }).click();
  expect(await panel.boundingBox()).toEqual(resized);
  const response = await page.request.get('/api/ai/conversations/private-diagnostic-probe?secret=private-query');
  expect(response.status()).toBe(404);
  await panel.getByRole('button', { name: '刷新日志', exact: true }).click();
  await expect(panel).toContainText('HTTP_404');
  await expect(panel).not.toContainText('private-diagnostic-probe');
  await expect(panel).not.toContainText('private-query');
  await panel.getByLabel('级别', { exact: true }).selectOption('error');
  await expect(panel).not.toContainText('HTTP_404');
  await panel.getByLabel('级别', { exact: true }).selectOption('warning');
  await expect(panel).toContainText(response.headers()['x-nautilus-request-id']);
  await panel.getByRole('button', { name: '暂停刷新' }).click();
  await expect(panel).toContainText('已暂停刷新，记录继续');
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  const panelBounds = await panel.boundingBox();
  const workspaceBounds = await page.locator('.v6-workspace').boundingBox();
  expect(workspaceBounds!.height).toBe(844);
  expect(panelBounds!.x).toBeGreaterThanOrEqual(0);
  expect(panelBounds!.x + panelBounds!.width).toBeLessThanOrEqual(390);
  expect(panelBounds!.y + panelBounds!.height).toBeLessThanOrEqual(844);
  await panel.getByRole('button', { name: '最大化日志' }).click();
  expect(await panel.boundingBox()).toEqual({ x: 0, y: 0, width: 390, height: 844 });
  await panel.getByRole('button', { name: '还原窗口' }).click();
  await panel.getByRole('button', { name: '最小化日志' }).click();
  await expect(panel).toHaveCount(0);
  await page.reload();
  await page.getByRole('button', { name: '日志', exact: true }).click();
  await expect(panel).toContainText('HTTP_404');
  page.once('dialog', dialog => void dialog.accept());
  await panel.getByRole('button', { name: '清空日志' }).click();
  await expect(panel).not.toContainText(response.headers()['x-nautilus-request-id']);
  await panel.getByRole('button', { name: '最小化日志' }).click();
  await page.setViewportSize({ width: 1280, height: 800 });
  await page.getByRole('button', { name: '设置', exact: true }).click();
  await settings.getByText('高级设置', { exact: true }).click();
  await settings.getByLabel('开启诊断日志').click();
  await expect(settings.getByLabel('开启诊断日志')).not.toBeChecked();
  await settings.getByRole('button', { name: '关闭', exact: true }).click();
  await expect(page.getByRole('button', { name: '日志', exact: true })).toHaveCount(0);
});
