import { expect, test } from '@playwright/test';
import { authorize } from './fact-helpers';

test('opt-in persistent diagnostic panel, filtering, collapse, clearing and disable', async ({ page }) => {
  await authorize(page);
  await expect(page.getByRole('button', { name: '日志', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: '设置', exact: true }).click();
  const settings = page.getByRole('dialog', { name: '设置', exact: true });
  await settings.getByText('高级设置', { exact: true }).click();
  await expect(settings.getByLabel('开启诊断日志')).not.toBeChecked();
  await settings.getByLabel('开启诊断日志').click();
  await expect(settings.getByLabel('开启诊断日志')).toBeChecked();
  await settings.getByRole('button', { name: '打开日志窗口' }).click();
  await expect(settings).toHaveCount(0);
  const panel = page.getByRole('region', { name: '诊断日志', exact: true });
  await expect(panel).toBeVisible();
  const response = await page.request.get('/api/ai/conversations/private-diagnostic-probe?secret=private-query');
  expect(response.status()).toBe(404);
  await panel.getByRole('button', { name: '刷新日志', exact: true }).click();
  await expect(panel).toContainText('HTTP_404');
  await expect(panel).not.toContainText('private-diagnostic-probe');
  await expect(panel).not.toContainText('private-query');
  await panel.getByLabel('级别', { exact: true }).selectOption('error');
  await expect(panel).not.toContainText('HTTP_404');
  await panel.getByLabel('级别', { exact: true }).selectOption('warning');
  await expect(panel).toContainText(response.headers()['x-nautilus-request-id']);
  await panel.getByRole('button', { name: '暂停刷新' }).click();
  await expect(panel).toContainText('已暂停刷新，记录继续');
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  const panelBounds = await panel.boundingBox();
  const workspaceBounds = await page.locator('.v6-workspace').boundingBox();
  expect(workspaceBounds!.y + workspaceBounds!.height).toBeLessThanOrEqual(panelBounds!.y + 1);
  await panel.getByRole('button', { name: '收起日志' }).click();
  await expect(panel).toHaveCount(0);
  await page.reload();
  await page.getByRole('button', { name: '日志', exact: true }).click();
  await expect(panel).toContainText('HTTP_404');
  page.once('dialog', dialog => void dialog.accept());
  await panel.getByRole('button', { name: '清空日志' }).click();
  await expect(panel).not.toContainText(response.headers()['x-nautilus-request-id']);
  await panel.getByRole('button', { name: '收起日志' }).click();
  await page.setViewportSize({ width: 1280, height: 800 });
  await page.getByRole('button', { name: '设置', exact: true }).click();
  await settings.getByText('高级设置', { exact: true }).click();
  await settings.getByLabel('开启诊断日志').click();
  await expect(settings.getByLabel('开启诊断日志')).not.toBeChecked();
  await settings.getByRole('button', { name: '关闭', exact: true }).click();
  await expect(page.getByRole('button', { name: '日志', exact: true })).toHaveCount(0);
});
