import { expect, test, type APIRequestContext, type Page } from '@playwright/test';
import { authorize, checkDefaultTeachingSupport } from './fact-helpers';
import type { CommitmentView, SessionFeedbackView } from '../src/learning-commitment-api';

test.setTimeout(60_000);
test.use({ actionTimeout: 10_000 });
const key = (name: string) => `d2-commitment:${name}:${Date.now()}:${Math.random().toString(36).slice(2, 7)}`;
async function get<T = any>(request: APIRequestContext, url: string): Promise<T> { const result = await request.get(url); expect(result.ok(), await result.text()).toBeTruthy(); return result.json(); }
async function post(request: APIRequestContext, url: string, data: object) { const result = await request.post(url, { data }); expect(result.ok(), await result.text()).toBeTruthy(); return result.json(); }
async function configure(page: Page, model = 'mock-success') {
  const result = await page.request.put('/api/ai/provider', { data: { display_name: 'Synthetic commitment provider', base_url: process.env.NAUTILUS_E2E_MOCK_PROVIDER_URL, model, api_key: 'synthetic-commitment-only', enabled: true, request_timeout_seconds: 15 } }); expect(result.ok()).toBeTruthy();
}
async function seed(request: APIRequestContext) {
  const plan = await post(request, '/api/learning/plans', { title: key('合成近期计划'), description: '', goal_id: null, request_key: key('plan') });
  const tasks: Array<{ title: string; action_id: string; delegation_id: string; outcome_id: string }> = [];
  for (const title of ['合成下一步任务', '合成边界任务']) {
    const organization = await get(request, `/api/learning/plans/${plan.plan_id}/organization`);
    const value = await post(request, `/api/learning/plans/${plan.plan_id}/tasks`, { action_title: title, context_key: '合成近期检查', object_description: '合成输入', behavior: '解释一个输入', outcome_context_key: '合成近期检查', outcome_id: null, criterion_id: null, boundaries: '仅此输入', stop_conditions: '解释后停下', time_budget_minutes: null, expected_revision: organization.revision, request_key: key('task') }); tasks.push({ ...value, title });
  }
  const url = `/api/learning/plans/${plan.plan_id}/path`, route = await get(request, url);
  const draft = await post(request, `${url}/drafts`, { title: '合成两步路线', nodes: tasks.map((task, index) => ({ id: `n${index}`, title: `合成阶段 ${index + 1}`, action_ids: [task.action_id], outcome_ids: [] })), edges: [{ source: 'n0', target: 'n1' }], entry_node_id: 'n0', current_node_id: 'n0', reason: '', intent: 'create', expected_revision: route.revision, expected_organization_revision: route.organization_revision, request_key: key('route') });
  const preview = await post(request, `${url}/previews`, { draft_id: draft.draft_id });
  const adopted = await post(request, `${url}/decisions`, { draft_id: draft.draft_id, expected_draft_revision: preview.draft_revision, expected_revision: preview.revision, review_key: preview.review_key, request_key: key('adopt') });
  return { id: plan.plan_id as string, tasks, routeId: adopted.adopted_version_id as string };
}
const base = (id: string) => `/api/learning/plans/${id}/commitments`;
const view = (page: Page, id: string) => get<CommitmentView>(page.request, base(id));
async function open(page: Page, id: string) { await page.goto(`/?view=plans&plan=${id}&plan_view=commitments`); await expect(page.getByRole('region', { name: '近期安排', exact: true })).toBeVisible(); await expect(page.getByRole('button', { name: '手动安排', exact: true })).toBeEnabled(); }
async function manual(page: Page, plan: Awaited<ReturnType<typeof seed>>) {
  await page.getByRole('button', { name: '手动安排', exact: true }).click(); const editor = page.getByRole('dialog', { name: '手动安排', exact: true });
  await editor.getByRole('button', { name: '添加一项', exact: true }).click(); await editor.getByRole('group', { name: '安排 1', exact: true }).getByLabel('计划任务', { exact: true }).selectOption(plan.tasks[0].delegation_id);
  await editor.getByRole('button', { name: '添加一项', exact: true }).click(); const second = editor.getByRole('group', { name: '安排 2', exact: true });
  await second.getByLabel('关联阶段', { exact: true }).selectOption('n1'); await second.getByLabel('计划任务', { exact: true }).selectOption(plan.tasks[1].delegation_id); await second.getByRole('button', { name: '向上', exact: true }).click();
  await editor.getByRole('textbox', { name: '这次安排的说明（可选）', exact: true }).fill('本人明确的合成安排说明'); return editor;
}

test('manual order and conflicts preserve inputs; start, feedback correction and purge retain work', async ({ page }) => {
  await authorize(page); await configure(page); await checkDefaultTeachingSupport(page); const plan = await seed(page.request); await open(page, plan.id);
  const initial = await get(page.request, '/api/learning/state');
  const editor = await manual(page, plan);
  const previous = await view(page, plan.id);
  await post(page.request, `${base(plan.id)}/availability`, { timezone: 'UTC', slots: [], weekly_budget_minutes: null, block_max_minutes: null, preferred_days: 7, expected_revision: previous.revision, request_key: key('concurrent') });
  await editor.getByRole('button', { name: '保存草案并预览', exact: true }).click(); await expect(editor).toContainText('编辑内容已保留'); await expect(editor.getByRole('textbox', { name: '这次安排的说明（可选）', exact: true })).toHaveValue('本人明确的合成安排说明');
  await editor.getByRole('button', { name: '读取最新状态', exact: true }).click(); await editor.getByRole('button', { name: '已核对，继续编辑', exact: true }).click(); await editor.getByRole('button', { name: '保存草案并预览', exact: true }).click();
  const preview = page.getByRole('dialog', { name: '确认近期安排', exact: true }); await expect(preview).toContainText('日期未知'); await expect(preview).toContainText('预计投入未知'); await preview.getByRole('button', { name: '取消', exact: true }).click();
  let current = await view(page, plan.id); expect(current.current_version).toBeNull(); expect((await get(page.request, '/api/learning/state')).sessions).toHaveLength(initial.sessions.length);
  await page.getByRole('button', { name: '查看确认预览', exact: true }).click(); await page.getByRole('dialog', { name: '确认近期安排', exact: true }).getByRole('button', { name: '确认采用安排', exact: true }).click();
  current = await view(page, plan.id); expect(current.current_version!.items.map(item => item.action_id)).toEqual([plan.tasks[1].action_id, plan.tasks[0].action_id]); const item = current.current_version!.items[0]; expect(item.due_at).toBeNull();
  await page.screenshot({ path: '/tmp/nautilus-d2-commitment-review-desktop.png', fullPage: true });
  await page.locator(`[data-commitment-item="${item.id}"]`).getByRole('button', { name: '开始学习', exact: true }).click(); await expect(page.getByRole('region', { name: '本次学习安排', exact: true })).toContainText(plan.tasks[1].title);
  let state = await get(page.request, '/api/learning/state'); const session = state.sessions.find((value: any) => value.delegation_id === plan.tasks[1].delegation_id && value.status === 'running'); expect(session).toBeTruthy();
  const artifact = await post(page.request, '/api/learning/artifacts', { session_id: session.id, content: '合成产出，保留事实。', expected_version: state.actions.find((action: any) => action.id === plan.tasks[1].action_id).version, idempotency_key: key('artifact') });
  await page.getByRole('button', { name: '今天先停', exact: true }).click();
  const feedback = page.locator('.session-feedback').first(); await feedback.locator(':scope > summary').click(); await expect(feedback.getByLabel('至少', { exact: true })).toHaveValue(''); await expect(feedback.getByLabel('至多', { exact: true })).toHaveValue('');
  await feedback.getByLabel('这次用于', { exact: true }).selectOption('test'); await feedback.getByLabel('本人感到', { exact: true }).selectOption('difficulty'); await feedback.getByText('关联已有产出或作答（可选）', { exact: true }).click(); await feedback.getByLabel('本次学习产出', { exact: true }).selectOption(artifact.id); await feedback.getByLabel('补充（可选）', { exact: true }).fill('合成本人体验，投入仍未知'); await feedback.getByRole('button', { name: '保存本人反馈', exact: true }).click(); await expect(feedback.getByRole('button', { name: '更正本人反馈', exact: true })).toBeVisible();
  let saved = await get<SessionFeedbackView>(page.request, `/api/learning/sessions/${session.id}/feedback`); expect(saved.current).toMatchObject({ actual_min_minutes: null, actual_max_minutes: null, artifact_id: artifact.id, purpose: 'test' });
  await feedback.getByRole('button', { name: '更正本人反馈', exact: true }).click(); await feedback.getByLabel('至少', { exact: true }).fill('12'); await feedback.getByLabel('至多', { exact: true }).fill('18'); await feedback.getByLabel('补充（可选）', { exact: true }).fill('合成更正体验');
  const { current: previousFeedback } = saved;
  await post(page.request, `/api/learning/sessions/${session.id}/feedback`, { actual_min_minutes: null, actual_max_minutes: null, purpose: 'test', grain: 'unknown', pace: 'unknown', method_feedback: 'unknown', progress: 'difficulty', activity: 'learning', artifact_id: artifact.id, artifact_version: previousFeedback!.artifact_version, submission_id: null, delayed_attempt_id: null, notes: '另一处明确更正的合成体验', expected_revision: saved.revision, request_key: key('feedback-concurrent') });
  await feedback.getByRole('button', { name: '保存本人反馈', exact: true }).click(); await expect(feedback).toContainText('已保留你的输入'); await expect(feedback.getByLabel('补充（可选）', { exact: true })).toHaveValue('合成更正体验'); await feedback.getByRole('button', { name: '读取最新反馈', exact: true }).click(); await feedback.getByRole('button', { name: '已核对，继续编辑', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 800 }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy(); await page.screenshot({ path: '/tmp/nautilus-d2-commitment-review-feedback-390.png', fullPage: true });
  await feedback.getByRole('button', { name: '保存本人反馈', exact: true }).click(); saved = await get(page.request, `/api/learning/sessions/${session.id}/feedback`); expect(saved.history).toHaveLength(3); expect(saved.current).toMatchObject({ actual_min_minutes: 12, actual_max_minutes: 18, notes: '合成更正体验' });
  await feedback.getByRole('button', { name: '内容清除', exact: true }).click(); await feedback.getByRole('button', { name: '清除本人反馈内容', exact: true }).click(); await page.getByRole('dialog', { name: '清除本人反馈内容', exact: true }).getByRole('button', { name: '确认清除', exact: true }).click();
  saved = await get(page.request, `/api/learning/sessions/${session.id}/feedback`); expect(saved.current).toBeNull(); expect(saved.history.every(entry => entry.notes === null)).toBeTruthy(); state = await get(page.request, '/api/learning/state'); expect(state.artifacts.some((value: any) => value.id === artifact.id && value.content === '合成产出，保留事实。')).toBeTruthy(); expect(state.sessions.some((value: any) => value.id === session.id)).toBeTruthy();
  await open(page, plan.id); await page.locator(`[data-commitment-item="${item.id}"]`).getByRole('button', { name: '查看记录', exact: true }).click(); await page.getByText('各次学习的本人体验', { exact: true }).click(); await page.locator('.session-feedback').first().locator(':scope > summary').click(); await expect(page.locator('.session-feedback').first()).toContainText('反馈内容已清除');
});

test('explicit local provider suggestions keep source refs through editing and never start automatically', async ({ page }) => {
  await authorize(page); await configure(page); const plan = await seed(page.request); const mock = process.env.NAUTILUS_E2E_MOCK_PROVIDER_URL!.replace(/\/v1$/, '');
  const before = (await get(page.request, `${mock}/__mock__/stats`)).requests['commitment:mock-success'] ?? 0; const sessions = (await get(page.request, '/api/learning/state')).sessions.length;
  await open(page, plan.id); await page.reload(); await expect(page.getByRole('button', { name: '更新近期安排', exact: true })).toBeEnabled(); expect((await get(page.request, `${mock}/__mock__/stats`)).requests['commitment:mock-success'] ?? 0).toBe(before);
  await page.getByRole('button', { name: '更新近期安排', exact: true }).click(); await expect(page.getByRole('region', { name: '候选安排', exact: true })).toBeVisible(); expect((await get(page.request, `${mock}/__mock__/stats`)).requests['commitment:mock-success']).toBe(before + 1);
  let current = await view(page, plan.id); const draft = current.drafts.find(value => value.status === 'draft')!; expect(draft.source).toBe('ai'); expect(draft.run_id).toBeTruthy(); expect(draft.items[0].source_refs.length).toBeGreaterThan(0);
  await page.getByRole('button', { name: '逐项编辑', exact: true }).click(); const editor = page.getByRole('dialog', { name: '编辑建议安排', exact: true }); await editor.getByRole('textbox', { name: '这次安排的说明（可选）', exact: true }).fill('本人核对合成建议'); await editor.getByRole('button', { name: '保存草案并预览', exact: true }).click();
  const preview = page.getByRole('dialog', { name: '确认近期安排', exact: true }); await preview.getByRole('button', { name: '确认采用安排', exact: true }).click(); await expect(preview).toHaveCount(0);
  current = await view(page, plan.id); const edited = current.drafts.find(value => value.id === draft.id)!; expect(edited.source).toBe('ai'); expect(edited.run_id).toBe(draft.run_id); expect(edited.items[0].source_refs).toEqual(draft.items[0].source_refs); expect(current.current_version!.source).toBe('ai'); expect((await get(page.request, '/api/learning/state')).sessions).toHaveLength(sessions);
  await configure(page, 'mock-slow'); await page.getByRole('button', { name: '更新近期安排', exact: true }).click(); await page.getByRole('button', { name: '取消更新', exact: true }).click(); await expect(page.locator('.commitment-run')).toContainText('已取消更新');
  await configure(page, 'mock-error'); await page.getByRole('button', { name: '更新近期安排', exact: true }).click(); await expect(page.locator('.commitment-run').getByRole('alert')).toContainText('未通过授权'); expect((await get(page.request, '/api/learning/state')).sessions).toHaveLength(sessions);
});

test('mobile arrangement previews pause only on confirm; skip retains facts and clear keeps arrangements', async ({ page }) => {
  await authorize(page); const plan = await seed(page.request); await open(page, plan.id); const editor = await manual(page, plan); await editor.getByRole('button', { name: '保存草案并预览', exact: true }).click(); await page.getByRole('dialog', { name: '确认近期安排', exact: true }).getByRole('button', { name: '确认采用安排', exact: true }).click();
  let current = await view(page, plan.id); const item = current.current_version!.items[0]; let state = await get(page.request, '/api/learning/state'); const started = await post(page.request, `${base(plan.id)}/items/${item.id}/start`, { expected_action_version: state.actions.find((action: any) => action.id === item.action_id).version, expected_revision: current.revision, use_checkpoint: true, request_key: key('start') });
  await page.reload();
  for (const width of [390, 320]) { await page.setViewportSize({ width, height: 780 }); await page.locator(`[data-commitment-item="${item.id}"]`).getByRole('button', { name: '改期', exact: true }).click(); const dialog = page.getByRole('dialog', { name: '改期', exact: true }); await expect(dialog).toBeVisible(); expect(await dialog.evaluate(node => node.scrollWidth <= node.clientWidth)).toBeTruthy(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy(); await dialog.getByRole('button', { name: '查看影响预览', exact: true }).click(); await expect(dialog).toContainText('确认后暂停相关学习'); if (width === 320) await page.screenshot({ path: '/tmp/nautilus-d2-commitment-review-arrangement-320.png', fullPage: true }); await dialog.getByRole('button', { name: '取消', exact: true }).click(); expect((await get(page.request, '/api/learning/state')).sessions.find((session: any) => session.id === started.session_id).status).toBe('running'); }
  await page.locator(`[data-commitment-item="${item.id}"]`).getByRole('button', { name: '改期', exact: true }).click(); let dialog = page.getByRole('dialog', { name: '改期', exact: true }); await dialog.getByRole('button', { name: '查看影响预览', exact: true }).click(); await dialog.getByRole('button', { name: '确认改期', exact: true }).click();
  state = await get(page.request, '/api/learning/state'); expect(state.sessions.find((session: any) => session.id === started.session_id).status).not.toBe('running'); current = await view(page, plan.id); expect(current.current_version!.items.find(value => value.id === item.id)!.execution_session_ids).toContain(started.session_id);
  await page.getByText('其他安排与已发生记录', { exact: true }).click(); await page.locator(`[data-commitment-item="${item.id}"]`).getByRole('button', { name: '跳过', exact: true }).click(); dialog = page.getByRole('dialog', { name: '跳过这项安排', exact: true }); await dialog.getByRole('button', { name: '查看影响预览', exact: true }).click(); await dialog.getByRole('button', { name: '确认跳过', exact: true }).click(); current = await view(page, plan.id); expect(current.current_version!.items.find(value => value.id === item.id)!.status).toBe('skipped');
  await page.getByText('安排历史与内容清除', { exact: true }).click(); await page.getByRole('button', { name: '内容清除', exact: true }).click(); await page.getByRole('button', { name: '清除安排说明', exact: true }).click(); await page.getByRole('dialog', { name: '清除安排说明', exact: true }).getByRole('button', { name: '确认清除', exact: true }).click(); current = await view(page, plan.id); expect(current.current_version!.reason).toBeNull(); expect(current.current_version!.items.find(value => value.id === item.id)!.status).toBe('skipped'); expect(current.current_version!.items.find(value => value.id === item.id)!.execution_session_ids).toContain(started.session_id);
  await post(page.request, `/api/learning/delegations/${plan.tasks[0].delegation_id}/completion`, { request_key: key('complete'), verification_kind: 'unverified', note: '合成执行完成，能力尚未验证。', report: null, material: null }); await page.reload(); await page.getByText('其他安排与已发生记录', { exact: true }).click(); const completedId = current.current_version!.items.find(value => value.action_id === plan.tasks[0].action_id)!.id; const completed = page.locator(`[data-commitment-item="${completedId}"]`); await expect(completed.getByRole('button', { name: '回看记录', exact: true })).toBeVisible(); await expect(completed.getByRole('button', { name: /开始学习|继续学习|改期|跳过/ })).toHaveCount(0);
});

test('refresh recovers one active update without generating again; failed history can reopen and purge', async ({ page }) => {
  await authorize(page); await configure(page, 'mock-slow'); const plan = await seed(page.request); await open(page, plan.id);
  const mock = process.env.NAUTILUS_E2E_MOCK_PROVIDER_URL!.replace(/\/v1$/, ''); const before = (await get(page.request, `${mock}/__mock__/stats`)).requests['commitment:mock-slow'] ?? 0;
  await page.getByRole('button', { name: '更新近期安排', exact: true }).click(); await expect(page.getByRole('button', { name: '取消更新', exact: true })).toBeVisible();
  let current = await view(page, plan.id); const running = current.runs!.find(value => value.status === 'running')!; expect(running).toBeTruthy(); expect(running).not.toHaveProperty('provider_snapshot'); expect(running).not.toHaveProperty('calibration');
  const duplicate = await page.request.post(`${base(plan.id)}/suggestions`, { data: { expected_revision: current.revision, request_key: key('other-tab') } }); expect(duplicate.status()).toBe(409); expect((await duplicate.json()).detail.kind).toBe('commitment_generation_running');
  await page.reload(); await expect(page.getByRole('button', { name: '取消更新', exact: true })).toBeVisible(); await expect(page.getByRole('button', { name: '更新近期安排', exact: true })).toBeDisabled(); expect((await get(page.request, `${mock}/__mock__/stats`)).requests['commitment:mock-slow']).toBe(before + 1);
  await page.getByRole('button', { name: '取消更新', exact: true }).click(); await expect(page.locator('.commitment-run')).toContainText('已取消更新');
  await configure(page, 'mock-error'); await page.reload(); await expect(page.getByRole('button', { name: '更新近期安排', exact: true })).toBeEnabled(); await page.getByRole('button', { name: '更新近期安排', exact: true }).click(); await expect(page.locator('.commitment-run').getByRole('alert')).toContainText('未通过授权');
  current = await view(page, plan.id); const failed = current.runs!.find(value => value.status === 'failed')!; expect(failed).toBeTruthy(); await page.reload(); await expect(page.locator('.commitment-run').getByRole('alert')).toContainText('未通过授权');
  await page.getByText('更新历史与内容清除', { exact: true }).click(); const history = page.locator(`[data-commitment-run="${failed.id}"]`); await expect(history).toContainText('未通过授权'); await history.getByRole('button', { name: '内容清除', exact: true }).click(); await history.getByRole('button', { name: '清除这次更新内容', exact: true }).click(); await page.getByRole('dialog', { name: '清除这次更新内容', exact: true }).getByRole('button', { name: '确认清除', exact: true }).click();
  const cleared = await get(page.request, `${base(plan.id)}/suggestions/${failed.id}`); expect(cleared).toMatchObject({ status: 'purged', content_available: false, can_purge_content: true }); await page.reload(); await page.getByText('更新历史与内容清除', { exact: true }).click(); await page.locator(`[data-commitment-run="${failed.id}"]`).getByRole('button', { name: '内容清除', exact: true }).click(); await expect(page.locator(`[data-commitment-run="${failed.id}"]`)).toContainText('已清除管理范围内的内容');
});
