import { expect, test } from '@playwright/test';
import { authorize } from './fact-helpers';

test('remove from library preserves source use, then library purge clears it', async ({ page }) => {
  test.setTimeout(90_000);
  await authorize(page);
  const routes = await (await page.request.get(`http://127.0.0.1:${process.env.NAUTILUS_E2E_BACKEND_PORT ?? '8012'}/openapi.json`)).json();
  expect(routes.paths['/api/materials/library/{material_id}/remove']).toBeTruthy();
  expect(routes.paths['/api/materials/library/{material_id}/purge']).toBeTruthy();

  await page.getByRole('button', { name: '学习室', exact: true }).click();
  await expect(page.locator('.ai-composer').getByRole('button', { name: /联网搜索/ })).toBeEnabled();
  await page.getByRole('button', { name: '新建对话', exact: true }).click();
  const materialsButton = page.locator('.ai-composer').getByRole('button', { name: /^资料(?: · \d+)?$/ });
  const panel = page.locator('.task-materials-panel');
  await materialsButton.click();
  await expect(panel.getByLabel(/上传资料/)).toBeEnabled();
  const upload = page.waitForResponse(response => /\/api\/materials\/conversation\/[^/]+\/upload$/.test(response.url()) && response.request().method() === 'POST');
  await panel.getByLabel(/上传资料/).setInputFiles({ name: '库内治理合成资料.txt', mimeType: 'text/plain', buffer: Buffer.from('合成资料内容，仅用于隔离测试。') });
  const uploaded = await upload;
  const version = await uploaded.json();
  const sourceId = new URL(uploaded.url()).pathname.split('/')[4];
  const materialId = version.material_id as string;
  await expect(panel.getByRole('checkbox', { name: '库内治理合成资料.txt · 文本资料' })).toBeChecked();
  await panel.getByRole('button', { name: '存入资料库' }).click();
  await expect(panel.getByText('已存入资料库')).toBeVisible();

  await page.getByRole('button', { name: '新建对话', exact: true }).click();
  await materialsButton.click();
  await panel.getByRole('button', { name: '从资料库选用' }).click();
  const library = panel.getByRole('region', { name: '资料库' });
  await expect(library.getByText(/库内治理合成资料.txt · 文本资料 · 1 个版本/)).toBeVisible();
  await expect(panel.getByRole('checkbox', { name: '库内治理合成资料.txt · 文本资料' })).toHaveCount(0);
  let removeRequests = 0;
  page.on('request', request => { if (request.method() === 'POST' && request.url().endsWith(`/api/materials/library/${materialId}/remove`)) removeRequests++; });
  await library.getByRole('button', { name: '从资料库移除' }).scrollIntoViewIfNeeded();
  await panel.screenshot({ path: '/tmp/nautilus-library-management-desktop.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  await library.getByRole('button', { name: '从资料库移除' }).scrollIntoViewIfNeeded();
  await panel.screenshot({ path: '/tmp/nautilus-library-management-mobile.png' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await library.getByRole('button', { name: '从资料库移除' }).click();
  const removeDialog = page.getByRole('dialog', { name: '从资料库移除这份资料？' });
  await expect(removeDialog).toContainText('已有对话中的资料引用和回答将保留');
  await expect(removeDialog.getByRole('button', { name: '确认移除' })).toBeInViewport();
  await removeDialog.screenshot({ path: '/tmp/nautilus-library-removal-confirmation.png' });
  await removeDialog.getByRole('button', { name: '取消' }).click();
  await expect(removeDialog).toHaveCount(0);
  expect(removeRequests).toBe(0);
  await library.getByRole('button', { name: '从资料库移除' }).click();
  await removeDialog.getByRole('button', { name: '确认移除' }).click();
  await expect(library.getByText(/库内治理合成资料.txt · 文本资料 · 1 个版本/)).toHaveCount(0);
  expect(removeRequests).toBe(1);
  expect((await (await page.request.get(`/api/materials/conversation/${sourceId}`)).json()).versions.find((item: {id: string}) => item.id === version.id).library).toBe(false);
  const original = await page.request.get(`/api/materials/conversation/${sourceId}/versions/${version.id}/original`);
  expect(original.ok()).toBeTruthy();
  expect((await original.body()).toString()).toContain('合成资料内容');

  expect((await page.request.post(`/api/materials/conversation/${sourceId}/${materialId}/library`)).ok()).toBeTruthy();
  await page.reload();
  await expect(page.locator('.ai-composer').getByRole('button', { name: /联网搜索/ })).toBeEnabled();
  await materialsButton.click();
  await panel.getByRole('button', { name: '从资料库选用' }).click();
  await expect(library.getByText(/库内治理合成资料.txt · 文本资料 · 1 个版本/)).toBeVisible();
  await library.getByText('更多操作').click();
  await library.getByRole('button', { name: '彻底清除资料' }).click();
  const purgeDialog = page.getByRole('dialog', { name: '清除这份资料？' });
  await expect(purgeDialog).toContainText('所有选用它的对话');
  const purgeRequest = page.waitForRequest(request => request.method() === 'POST' && request.url().endsWith(`/api/materials/library/${materialId}/purge`));
  await purgeDialog.getByRole('button', { name: '确认清除' }).click();
  await purgeRequest;
  await expect(library.getByText(/库内治理合成资料.txt · 文本资料 · 1 个版本/)).toHaveCount(0);
  expect((await (await page.request.get(`/api/materials/conversation/${sourceId}`)).json()).versions.every((item: {purged_at: string | null}) => !!item.purged_at)).toBeTruthy();
  expect((await page.request.get(`/api/materials/conversation/${sourceId}/versions/${version.id}/original`)).ok()).toBe(false);
});

test('library partial purge has a retry entry after reopening', async ({ page }) => {
  await authorize(page);
  await page.getByRole('button', { name: '学习室', exact: true }).click();
  await expect(page.locator('.ai-composer').getByRole('button', { name: /联网搜索/ })).toBeEnabled();
  await page.getByRole('button', { name: '新建对话', exact: true }).click();
  const materialsButton = page.locator('.ai-composer').getByRole('button', { name: /^资料(?: · \d+)?$/ });
  const panel = page.locator('.task-materials-panel');
  await materialsButton.click();
  await expect(panel.getByLabel(/上传资料/)).toBeEnabled();
  const upload = page.waitForResponse(response => /\/api\/materials\/conversation\/[^/]+\/upload$/.test(response.url()) && response.request().method() === 'POST');
  await panel.getByLabel(/上传资料/).setInputFiles({ name: '重试合成资料.txt', mimeType: 'text/plain', buffer: Buffer.from('重试合成内容') });
  const version = await (await upload).json();
  await panel.getByRole('button', { name: '存入资料库' }).click();
  await expect(panel.getByText('已存入资料库')).toBeVisible();
  await page.getByRole('button', { name: '新建对话', exact: true }).click();
  await materialsButton.click();
  let retryPending = true;
  await page.route('**/api/materials/library', async route => {
    const response = await route.fetch();
    const data = await response.json();
    await route.fulfill({ response, json: retryPending ? { ...data, versions: [], purge_retry_ids: [version.material_id] } : data });
  });
  await page.route(`**/api/materials/library/${version.material_id}/purge`, async route => {
    const response = await route.fetch();
    retryPending = false;
    await route.fulfill({ response });
  });
  await panel.getByRole('button', { name: '从资料库选用' }).click();
  const library = panel.getByRole('region', { name: '资料库' });
  await expect(library.getByRole('button', { name: '重试清除' })).toBeVisible();
  await page.reload();
  await expect(page.locator('.ai-composer').getByRole('button', { name: /联网搜索/ })).toBeEnabled();
  await materialsButton.click();
  await panel.getByRole('button', { name: '从资料库选用' }).click();
  await library.getByRole('button', { name: '重试清除' }).click();
  const dialog = page.getByRole('dialog', { name: '清除这份资料？' });
  await expect(dialog).toBeVisible();
  await dialog.getByRole('button', { name: '确认清除' }).click();
  await expect(library.getByRole('button', { name: '重试清除' })).toHaveCount(0);
});
