import { expect, test } from '@playwright/test';
import { authorize } from './fact-helpers';

test('library versions can be selected across conversations and survive source deletion', async ({ page }) => {
  test.setTimeout(90_000);
  await authorize(page);
  const routes = await (await page.request.get(`http://127.0.0.1:${process.env.NAUTILUS_E2E_BACKEND_PORT ?? '8012'}/openapi.json`)).json();
  expect(routes.paths['/api/materials/library']).toBeTruthy();
  expect(routes.paths['/api/materials/{scope_kind}/{scope_id}/{material_id}/library']).toBeTruthy();
  expect(routes.paths['/api/materials/{scope_kind}/{scope_id}/library-use']).toBeTruthy();
  const provider = await page.request.put('/api/ai/provider', { data: {
    display_name: 'Library mock provider', base_url: process.env.NAUTILUS_E2E_MOCK_PROVIDER_URL ?? 'http://127.0.0.1:8013/v1',
    model: 'mock-success', api_key: 'synthetic-library-key', enabled: true, request_timeout_seconds: 15, api_protocol: 'openai_compatible',
  } });
  expect(provider.ok()).toBeTruthy();
  await page.reload();
  await page.getByRole('button', { name: '学习室', exact: true }).click();
  await expect(page.locator('.ai-composer').getByRole('button', { name: /联网搜索/ })).toBeEnabled();
  await page.getByRole('button', { name: '新建对话', exact: true }).click();
  const materialsButton = page.locator('.ai-composer').getByRole('button', { name: /^资料(?: · \d+)?$/ });
  await materialsButton.click();
  const panel = page.locator('.task-materials-panel');
  await expect(panel.getByLabel(/上传资料/)).toBeEnabled();
  const upload = page.waitForResponse(response => /\/api\/materials\/conversation\/[^/]+\/upload$/.test(response.url()) && response.request().method() === 'POST');
  await panel.getByLabel(/上传资料/).setInputFiles({ name: '跨对话教材.txt', mimeType: 'text/plain', buffer: Buffer.from('第一版：合成概念甲。') });
  const uploaded = await upload;
  const first = await uploaded.json();
  const sourceId = new URL(uploaded.url()).pathname.split('/')[4];
  await expect(panel.getByRole('checkbox', { name: '跨对话教材.txt · 文本资料' })).toBeChecked();
  await expect(panel.getByRole('button', { name: '存入资料库' })).toBeVisible();
  await panel.getByRole('button', { name: '存入资料库' }).click();
  await expect(panel.getByText('已存入资料库')).toBeVisible();
  await panel.getByText('查看当前版本和历史').click();
  await panel.getByRole('button', { name: '编辑为新版本' }).click();
  await panel.getByLabel('正文').fill('第二版：合成概念乙。');
  await panel.getByRole('button', { name: '保存版本' }).click();
  await expect(panel.getByText('第 2 版 · 跨对话教材.txt · 当前使用')).toBeVisible();

  await page.getByRole('button', { name: '新建对话', exact: true }).click();
  await materialsButton.click();
  await panel.getByRole('button', { name: '从资料库选用' }).click();
  await panel.locator('.task-material-library').getByText(/跨对话教材.txt · 文本资料 · 2 个版本/).click();
  await expect(panel.locator('.task-material-library').getByText('第 1 版 · 跨对话教材.txt')).toBeVisible();
  await expect(panel.getByText('第 2 版 · 跨对话教材.txt')).toBeVisible();
  await panel.getByRole('button', { name: '选用第 1 版' }).click();
  await expect(panel.getByRole('checkbox', { name: '跨对话教材.txt · 文本资料' })).toBeChecked();
  await expect(panel.locator('.task-material-library').getByText('第 1 版 · 跨对话教材.txt · 当前使用', { exact: true })).toBeVisible();
  await panel.getByText('查看当前版本和历史').click();
  const original = page.waitForEvent('download');
  await panel.getByRole('link', { name: '下载原件：跨对话教材.txt' }).click();
  expect((await original).suggestedFilename()).toBe('跨对话教材.txt');
  await materialsButton.click();
  const question = page.getByLabel('输入学习问题');
  await question.fill('请依据合成概念甲解释');
  const sent = page.waitForRequest(request => request.url().endsWith('/messages') && request.method() === 'POST');
  await question.press('Enter');
  const request = await sent;
  expect(request.postDataJSON().source_scope.version_ids).toEqual([first.id]);
  const { run } = await (await request.response())!.json();
  const secondId = run.conversation_id as string;
  await expect.poll(async () => (await (await page.request.get(`/api/ai/conversations/${secondId}`)).json()).active_run).toBeNull();
  await materialsButton.click();
  await panel.getByRole('checkbox', { name: '跨对话教材.txt · 文本资料' }).click();
  await expect(panel.getByRole('checkbox', { name: '跨对话教材.txt · 文本资料' })).not.toBeChecked();
  expect((await (await page.request.get('/api/materials/library')).json()).versions.some((item: {id: string}) => item.id === first.id)).toBeTruthy();
  await expect(panel.getByText('已存入资料库')).toBeVisible();
  expect((await page.request.delete(`/api/ai/conversations/${sourceId}`)).status()).toBe(204);
  await page.reload();
  await expect(page.locator('.ai-composer').getByRole('button', { name: /联网搜索/ })).toBeEnabled();
  await materialsButton.click();
  await panel.getByRole('button', { name: '从资料库选用' }).click();
  await panel.locator('.task-material-library').getByText(/跨对话教材.txt · 文本资料 · 2 个版本/).click();
  await expect(panel.getByRole('button', { name: '选用第 2 版' })).toBeVisible();
  await panel.getByRole('button', { name: '选用第 2 版' }).click();
  const selected = await (await page.request.get(`/api/materials/conversation/${secondId}`)).json();
  expect(selected.versions.map((item: { id: string }) => item.id)).toContain(first.id);
  const latest = selected.versions.find((item: { version: number; library: boolean }) => item.version === 2 && item.library);
  expect(latest).toBeTruthy();
  await materialsButton.click();
  await question.fill('请依据合成概念乙解释');
  const next = page.waitForRequest(item => item.url().endsWith('/messages') && item.method() === 'POST');
  await question.press('Enter');
  expect((await next).postDataJSON().source_scope.version_ids).toEqual([latest.id]);
  await expect.poll(async () => (await (await page.request.get(`/api/ai/conversations/${secondId}`)).json()).active_run).toBeNull();
  const history = await (await page.request.get(`/api/ai/conversations/${secondId}`)).json();
  const earlier = history.messages.find((item: {ai_run_id: string; role: string}) => item.ai_run_id === run.id && item.role === 'assistant');
  expect(earlier.source_scope.version_ids).toEqual([first.id]);
  await page.setViewportSize({ width: 390, height: 844 });
  await materialsButton.click();
  if (await panel.getByRole('button', { name: '从资料库选用' }).getAttribute('aria-expanded') === 'false') await panel.getByRole('button', { name: '从资料库选用' }).click();
  await panel.locator('.task-material-library summary').first().click();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.screenshot({ path: '/tmp/nautilus-library-mobile.png' });
  await panel.getByRole('button', { name: '清除', exact: true }).click();
  const confirmation = page.getByRole('dialog', { name: '清除这份资料？' });
  await expect(confirmation).toContainText('包括资料库中的共享资料');
  await confirmation.getByRole('button', { name: '确认清除' }).click();
  await expect(panel.getByRole('status')).toContainText('资料及关联内容已清除');
  expect((await (await page.request.get('/api/materials/library')).json()).versions).toEqual([]);
  const cleared = await (await page.request.get(`/api/ai/conversations/${secondId}`)).json();
  expect(cleared.messages.filter((item: {role: string}) => item.role === 'assistant').every((item: {content: string}) => !item.content)).toBeTruthy();
});
