import { expect, test, type Page } from '@playwright/test';
import { authorize } from './fact-helpers';
import type { AiConversationDetail, AiProvider, ModelConfig, ModelOverride, QuestionDiscussion, ReasoningChoice, ReasoningSupport } from '../src/api';

test.beforeEach(async ({ page }) => {
  const schema = await (await page.request.get(`http://127.0.0.1:${process.env.NAUTILUS_E2E_BACKEND_PORT ?? '8012'}/openapi.json`)).json();
  expect(schema.paths['/api/ai/provider/reasoning-preview']).toBeTruthy();
});
async function declare(page: Page, provider: AiProvider, modelId: string, profile = 'openai_o', defaultChoice?: ReasoningChoice) {
  const path = `/api/ai/providers/${provider.id}/models/${modelId}/reasoning-support`;
  const before = await (await page.request.get(path)).json() as ReasoningSupport;
  const response = await page.request.put(path, { data: { expected_revision: before.revision, profile_id: profile, ...(defaultChoice ? { default_choice: defaultChoice } : {}) } });
  expect(response.ok()).toBeTruthy();
}
async function configure(page: Page, model = 'mock-success', profile = 'openai_o', defaultChoice?: ReasoningChoice) {
  await authorize(page); const response = await page.request.put('/api/ai/provider', { data: {
    display_name: '合成思考控制', base_url: process.env.NAUTILUS_E2E_MOCK_PROVIDER_URL, model,
    api_key: 'synthetic-reasoning-control-key', enabled: true, request_timeout_seconds: 15,
  } });
  expect(response.ok()).toBeTruthy(); const { provider } = await response.json() as { provider: AiProvider };
  await declare(page, provider, provider.default_model_id!, profile, defaultChoice); await page.reload(); return provider;
}
async function addModel(page: Page, provider: AiProvider, modelId: string, displayName: string, profile: string) {
  const response = await page.request.post(`/api/ai/providers/${provider.id}/models/manual`, { data: { model_id: modelId, display_name: displayName } });
  expect(response.ok()).toBeTruthy(); const { model } = await response.json(); await declare(page, provider, model.id, profile); return model.id as string;
}
async function config(page: Page, kind: string, id: string): Promise<ModelConfig> { const response = await page.request.get(`/api/model-config/${kind}/${id}`); expect(response.ok()).toBeTruthy(); return response.json(); }
async function save(page: Page, kind: string, id: string, override: ModelOverride) {
  const before = await config(page, kind, id); const response = await page.request.put(`/api/model-config/${kind}/${id}`, { data: { expected_revision: before.revision, override } }); expect(response.ok()).toBeTruthy(); return response.json() as Promise<ModelConfig>;
}
async function currentId(page: Page) { return JSON.parse(await page.evaluate(() => sessionStorage.getItem('nautilus.ai.learning-room')) ?? '{}').conversationId as string; }
async function room(page: Page) { await page.getByRole('button', { name: '学习室', exact: true }).click(); await page.getByRole('button', { name: '新建对话', exact: true }).click(); }
const quick = (page: Page) => page.getByRole('button', { name: '思考设置', exact: true });
const popup = (page: Page) => page.getByRole('dialog', { name: '思考设置', exact: true });
const slider = (page: Page) => popup(page).getByRole('slider', { name: '思考强度', exact: true });
async function open(page: Page) { await expect(quick(page)).toBeEnabled(); if (!(await popup(page).count())) await quick(page).click(); await expect(slider(page)).toBeEnabled(); }
async function pick(page: Page, label: string) { await open(page); await popup(page).getByRole('button', { name: `设为${label}`, exact: true }).click(); await expect(slider(page)).toBeEnabled(); await expect(slider(page)).toHaveAttribute('aria-valuetext', label); await page.keyboard.press('Escape'); }
async function send(page: Page, text: string) {
  const accepted = page.waitForResponse(response => /\/api\/ai\/conversations\/[^/]+\/messages$/.test(response.url()) && response.request().method() === 'POST');
  const input = page.getByLabel('输入学习问题', { exact: true }); await input.fill(text); await input.press('Enter'); const response = await accepted; expect(response.ok()).toBeTruthy(); return response;
}
async function finished(page: Page, id: string): Promise<AiConversationDetail> {
  await expect.poll(async () => (await (await page.request.get(`/api/ai/conversations/${id}`)).json()).active_run, { timeout: 20_000 }).toBeNull(); await expect(page.getByRole('button', { name: '取消生成', exact: true })).toHaveCount(0); return (await page.request.get(`/api/ai/conversations/${id}`)).json();
}

test('slider prepares an empty conversation, previews drag until release, rolls back failure, and freezes active answers', async ({ page }) => {
  test.setTimeout(90_000); await configure(page, 'mock-slow'); await room(page); const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  const input = page.getByLabel('输入学习问题', { exact: true }); await input.fill('合成思考控制原草稿'); await open(page); const id = await currentId(page); expect(id).toBeTruthy();
  await expect(slider(page)).toHaveAttribute('max', '2'); await expect(slider(page)).toHaveAttribute('aria-valuetext', '高');
  await expect(popup(page)).not.toContainText('仅本次'); await expect(popup(page)).not.toContainText('恢复继承'); await expect(popup(page)).not.toContainText('模型默认'); await expect(popup(page)).not.toContainText('配置模型思考规格');
  const before = await config(page, 'conversation', id); expect(before.effective.reasoning).toEqual({ mode: 'effort', effort: 'high' }); expect(before.sources.reasoning?.kind).toBe('model');
  const box = (await slider(page).boundingBox())!; await page.mouse.move(box.x + box.width - 8, box.y + box.height / 2); await page.mouse.down(); await page.mouse.move(box.x + 3, box.y + box.height / 2, { steps: 5 });
  await expect(slider(page)).toHaveAttribute('aria-valuetext', '低'); expect((await config(page, 'conversation', id)).override.reasoning).toBeNull(); await page.mouse.up(); await expect.poll(async () => (await config(page, 'conversation', id)).override.reasoning).toEqual({ mode: 'effort', effort: 'low' });
  await page.route('**/api/model-config/conversation/*', async route => { if (route.request().method() === 'PUT') await route.fulfill({ status: 400, json: { detail: '合成保存失败' } }); else await route.continue(); });
  await popup(page).getByRole('button', { name: '设为高', exact: true }).click(); await expect(popup(page).getByRole('alert')).toContainText('合成保存失败'); await expect(slider(page)).toHaveAttribute('aria-valuetext', '低'); expect((await config(page, 'conversation', id)).override.reasoning).toEqual({ mode: 'effort', effort: 'low' });
  await page.unroute('**/api/model-config/conversation/*'); await popup(page).getByRole('button', { name: '设为高', exact: true }).click(); await expect(slider(page)).toBeEnabled(); await page.keyboard.press('Escape'); await expect(quick(page)).toBeFocused(); await expect(input).toHaveValue('合成思考控制原草稿');
  await send(page, '合成运行冻结检查'); await expect(page.getByRole('button', { name: '取消生成', exact: true })).toBeVisible(); await expect(quick(page)).toBeEnabled(); await pick(page, '中');
  const saved = await finished(page, id); const answer = saved.messages.at(-1)!; expect(answer.model_config).toMatchObject({ reasoning: { mode: 'effort', effort: 'high' }, reasoning_parameters: { reasoning_effort: 'high' } }); expect((await config(page, 'conversation', id)).override.reasoning).toEqual({ mode: 'effort', effort: 'medium' });
  await open(page); await page.screenshot({ path: '/tmp/nautilus-reasoning-slider-desktop.png', fullPage: true }); await page.keyboard.press('Escape'); await page.setViewportSize({ width: 390, height: 844 }); await open(page);
  const bounds = (await popup(page).boundingBox())!; expect(bounds.x).toBeGreaterThanOrEqual(0); expect(bounds.x + bounds.width).toBeLessThanOrEqual(390); expect(bounds.y).toBeGreaterThanOrEqual(0); expect(bounds.y + bounds.height).toBeLessThanOrEqual(844);
  await page.screenshot({ path: '/tmp/nautilus-reasoning-slider-mobile.png', fullPage: true }); await page.keyboard.press('Escape'); await expect(quick(page)).toBeFocused(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy(); expect(errors).toEqual([]);
});

test('three and five actual tiers follow selected models; temporary model thought stays bound to this conversation', async ({ page }) => {
  test.setTimeout(60_000); const provider = await configure(page); const five = await addModel(page, provider, 'synthetic-five-levels', '合成五档模型', 'openai_gpt6'); await page.reload(); await room(page); await pick(page, '低'); const id = await currentId(page);
  await page.getByRole('button', { name: '对话配置', exact: true }).click(); const panel = page.locator('#ai-conversation-config-panel'); await expect(panel.getByLabel('思考设置', { exact: true })).toHaveCount(0); await panel.getByLabel('模型配置选择').selectOption(`${provider.id}::${five}`); await panel.getByRole('button', { name: '保存配置', exact: true }).click(); await expect(panel).toContainText('合成五档模型'); await page.getByRole('button', { name: '对话配置', exact: true }).click();
  await open(page); await expect(slider(page)).toHaveAttribute('max', '4'); await expect(slider(page)).toHaveAttribute('aria-valuetext', '高'); await popup(page).getByRole('button', { name: '设为最高', exact: true }).click(); await expect(slider(page)).toBeEnabled(); await page.keyboard.press('Escape');
  await page.getByRole('button', { name: '对话配置', exact: true }).click(); await panel.getByRole('button', { name: '恢复继承', exact: true }).click(); await expect(panel).toContainText('mock-success'); await page.getByRole('button', { name: '对话配置', exact: true }).click(); await expect(quick(page)).toContainText('高'); await open(page); await expect(slider(page)).toHaveAttribute('max', '2'); await page.keyboard.press('Escape');
  await page.getByRole('button', { name: '对话配置', exact: true }).click(); await panel.getByRole('button', { name: '仅本次', exact: true }).click(); await panel.getByLabel('模型配置选择').selectOption(`${provider.id}::${five}`); await panel.getByLabel('模型配置超时').fill('42'); await panel.getByRole('button', { name: '用于本次', exact: true }).click(); await page.getByRole('button', { name: '对话配置', exact: true }).click(); await pick(page, '中');
  const persistent = await config(page, 'conversation', id); expect(persistent.override.model).toBeNull(); expect(persistent.override.timeout_seconds).toBeNull(); expect(persistent.override.reasoning_model).toEqual({ provider_profile_id: provider.id, provider_model_id: five }); expect(persistent.effective.reasoning).toEqual({ mode: 'effort', effort: 'high' });
  const accepted = await send(page, '合成仅本次模型与对话思考绑定'); expect(accepted.request().postDataJSON().model_override).toEqual({ model: { provider_profile_id: provider.id, provider_model_id: five }, timeout_seconds: 42 }); const saved = await finished(page, id); expect(saved.messages.at(-1)!.model_config).toMatchObject({ reasoning: { mode: 'effort', effort: 'medium' }, timeout_seconds: 42, sources: { reasoning: { kind: 'conversation' } } }); await expect(quick(page)).toContainText('高');
  await page.getByRole('button', { name: '新建对话', exact: true }).click(); await open(page); const second = await currentId(page); expect(second).not.toBe(id); expect((await config(page, 'conversation', second)).override.reasoning).toBeNull(); await expect(slider(page)).toHaveAttribute('aria-valuetext', '高');
});

test('Provider form saves model defaults, requires a real default without high, and discards stale preview results', async ({ page }) => {
  test.setTimeout(60_000); const provider = await configure(page); await page.getByRole('button', { name: '设置', exact: true }).click(); await page.getByRole('button', { name: '打开提供方设置', exact: true }).click(); const dialog = page.getByRole('dialog', { name: 'AI 提供方设置', exact: true });
  await expect(dialog.getByLabel('默认思考强度', { exact: true })).toHaveValue('effort:high');
  const discoveries: Record<string, unknown>[] = []; page.on('request', request => { if (request.method() === 'POST' && request.url().endsWith('/api/ai/provider/models')) discoveries.push(request.postDataJSON()); });
  await dialog.getByLabel('模型', { exact: true }).fill('synthetic-no-high'); await dialog.locator('.provider-reasoning details > summary').click(); await dialog.getByLabel('模型思考规格', { exact: true }).selectOption('qwen38'); await expect(dialog).toContainText('这个模型没有高档'); await expect(dialog.getByRole('button', { name: '保存配置', exact: true })).toBeDisabled();
  await dialog.getByLabel('默认思考强度', { exact: true }).selectOption('effort:medium'); await expect(dialog.getByRole('button', { name: '保存配置', exact: true })).toBeEnabled();
  const accepted = page.waitForResponse(response => response.url().endsWith(`/api/ai/providers/${provider.id}`) && response.request().method() === 'PATCH'); await dialog.getByRole('button', { name: '保存配置', exact: true }).click(); const response = await accepted; expect(response.ok()).toBeTruthy(); expect(response.request().postDataJSON().reasoning_settings).toEqual({ profile_id: 'qwen38', default_choice: { mode: 'effort', effort: 'medium' } }); await expect(dialog).toContainText('配置已保存');
  const changed = (await response.json()).provider as AiProvider; const support = await (await page.request.get(`/api/ai/providers/${provider.id}/models/${changed.default_model_id}/reasoning-support`)).json() as ReasoningSupport; expect(support.configured_default).toEqual({ mode: 'effort', effort: 'medium' });
  expect(discoveries.length).toBeGreaterThan(0); expect(discoveries.every(item => item.provider_id === provider.id)).toBeTruthy();
  let release: () => void = () => {}; const held = new Promise<void>(resolve => { release = resolve; });
  await page.route('**/api/ai/provider/reasoning-preview', async route => { if (route.request().postDataJSON().model === 'o3') { const result = await route.fetch(); await held; await route.fulfill({ response: result }); } else await route.continue(); });
  await dialog.getByLabel('模型', { exact: true }).fill('o3'); await expect(dialog.getByRole('button', { name: '保存配置', exact: true })).toBeDisabled(); await dialog.getByLabel('模型', { exact: true }).fill('gpt-6-astra'); await expect(dialog.getByLabel('默认思考强度', { exact: true })).toHaveValue('effort:high'); release(); await expect(dialog.getByLabel('默认思考强度', { exact: true })).toHaveValue('effort:high'); await expect(dialog.getByLabel('默认思考强度', { exact: true }).locator('option')).toHaveCount(5); await expect(dialog.getByLabel('模型', { exact: true })).toHaveValue('gpt-6-astra'); await page.unroute('**/api/ai/provider/reasoning-preview');
  await dialog.getByLabel('默认思考强度', { exact: true }).selectOption('effort:low'); await dialog.getByRole('button', { name: '保存配置', exact: true }).click(); await expect(dialog).toContainText('配置已保存'); await dialog.getByRole('button', { name: '关闭 AI 提供方设置', exact: true }).click(); const settings = page.getByRole('dialog', { name: '设置', exact: true }); if (await settings.isVisible()) await settings.getByRole('button', { name: '关闭设置', exact: true }).click(); await room(page); await open(page); await expect(slider(page)).toHaveAttribute('aria-valuetext', '低');
});

test('true Off is a real leftmost setting, literal budgets remain numeric, and new requests contain no once reasoning', async ({ page }) => {
  test.setTimeout(60_000); await configure(page, 'mock-success', 'deepseek_v4'); await room(page); await open(page); await expect(slider(page)).toHaveAttribute('max', '3'); await expect(popup(page).locator('.reasoning-slider-labels button').first()).toHaveText('关闭'); await expect(popup(page)).not.toContainText('开启'); await page.keyboard.press('Escape'); await pick(page, '关闭'); const id = await currentId(page); const accepted = await send(page, '合成关闭思考'); expect(accepted.request().postDataJSON().model_override).toBeNull(); const saved = await finished(page, id); expect(saved.messages.at(-1)!.model_config).toMatchObject({ reasoning: { mode: 'off' }, reasoning_parameters: { thinking: { type: 'disabled' } } });
  const provider = await (await page.request.get('/api/ai/provider')).json() as { provider: AiProvider }; await declare(page, provider.provider, provider.provider.default_model_id!, 'qwen_budget', { mode: 'budget', budget_tokens: 256 }); await page.evaluate(() => window.dispatchEvent(new Event('nautilus:model-settings-changed'))); await page.getByRole('button', { name: '新建对话', exact: true }).click(); await quick(page).click(); await expect(popup(page).getByLabel('思考预算方式')).toBeEnabled(); await expect(popup(page).getByRole('slider')).toHaveCount(0); await expect(popup(page).getByLabel('思考预算（Token）')).toHaveValue('256'); await popup(page).getByLabel('思考预算（Token）').fill('512'); await popup(page).getByRole('button', { name: '保存', exact: true }).click(); await expect(quick(page)).toContainText('512 Token'); await page.keyboard.press('Escape'); const budgetId = await currentId(page); await send(page, '合成实际思考预算'); const budgetAnswer = await finished(page, budgetId); expect(budgetAnswer.messages.at(-1)!.model_config).toMatchObject({ reasoning: { mode: 'budget', budget_tokens: 512 }, reasoning_parameters: { enable_thinking: true, thinking_budget: 512 } });
});

test('unknown acceptance retries its original current-conversation reasoning snapshot after settings change', async ({ page }) => {
  test.setTimeout(60_000); await configure(page); await room(page); await pick(page, '低'); const id = await currentId(page); const requests: Record<string, unknown>[] = []; let drop = true;
  await page.route('**/api/ai/conversations/*/messages', async route => { if (route.request().method() !== 'POST') { await route.continue(); return; } requests.push(route.request().postDataJSON()); const response = await route.fetch(); if (drop) { drop = false; await route.abort('failed'); } else await route.fulfill({ response }); });
  const input = page.getByLabel('输入学习问题', { exact: true }); await input.fill('合成思考未知接受'); await input.press('Enter'); await expect(input).toHaveValue('合成思考未知接受'); await expect(quick(page)).toBeDisabled(); await save(page, 'conversation', id, { reasoning: { mode: 'effort', effort: 'high' } }); await input.press('Enter'); await expect.poll(() => requests.length).toBe(2); expect(requests[1].client_message_id).toBe(requests[0].client_message_id); expect(requests[1].model_override).toEqual(requests[0].model_override); expect(requests[1].model_config_token).toBe(requests[0].model_config_token); const saved = await finished(page, id); expect(saved.messages).toHaveLength(2); expect(saved.messages.at(-1)!.model_config).toMatchObject({ reasoning: { mode: 'effort', effort: 'low' } });
});

test('discussion uses current-conversation tiers and keeps the accepted reasoning in history', async ({ page }) => {
  test.setTimeout(90_000); await configure(page); await page.getByRole('button', { name: '学习首页', exact: true }).click(); if (await (await page.request.get('/api/learning/return-review')).json()) await page.getByRole('button', { name: '创建', exact: true }).click(); await page.getByLabel('学习目标', { exact: true }).fill('合成目标：讨论思考控制'); await page.getByRole('button', { name: '我想自己安排', exact: true }).click(); await page.getByLabel('现在先做什么', { exact: true }).fill('合成讨论思考任务'); await page.getByRole('button', { name: '确认这份学习安排', exact: true }).click(); await page.getByRole('button', { name: '进入学习室并开始这项任务', exact: true }).click(); await expect(page.getByRole('button', { name: '取消生成', exact: true })).toHaveCount(0); await page.getByRole('button', { name: '进入验证', exact: true }).click(); await page.getByRole('button', { name: '开始验证', exact: true }).click(); await page.getByPlaceholder('写出你的判断、过程或结果').fill('合成作答：核对边界。'); await page.getByRole('button', { name: '保存作答并验证', exact: true }).click(); await page.getByRole('region', { name: '验证回看' }).getByRole('article', { name: '第 1 题回看' }).getByRole('button', { name: '讨论这道题', exact: true }).click();
  await pick(page, '低'); const id = new URL(page.url()).searchParams.get('discussion')!; const accepted = page.waitForResponse(response => response.url().endsWith(`/api/learning/discussions/${id}/messages`) && response.request().method() === 'POST'); const room = page.getByRole('region', { name: '题目学习室' }); const input = room.getByLabel('继续提问或回答拓展问题'); await input.fill('合成讨论思考问题'); await input.press('Enter'); const response = await accepted; expect(response.ok()).toBeTruthy(); expect(response.request().postDataJSON().model_override).toBeNull(); await pick(page, '中'); await expect.poll(async () => (await (await page.request.get(`/api/learning/discussions/${id}`)).json() as QuestionDiscussion).turns.at(-1)?.status, { timeout: 15_000 }).toBe('succeeded'); await page.reload(); await expect(input).toBeEnabled(); await expect(quick(page)).toContainText('中'); const history = room.locator('.model-config-history'); await history.locator(':scope > summary').click(); await expect(history).toContainText('思考 低'); await page.setViewportSize({ width: 390, height: 844 }); await open(page); const bounds = (await popup(page).boundingBox())!; expect(bounds.x + bounds.width).toBeLessThanOrEqual(390); await page.screenshot({ path: '/tmp/nautilus-reasoning-slider-discussion-mobile.png', fullPage: true }); await page.keyboard.press('Escape');
});
